### ISSUE TITLE
Attributes in cl_information do not display properly if any decimals are involved.

### ISSUE THREAD

**Issue by Chancerawr** [rebel1324/NutScript#10]
Problem happens in cl_information on this line:
bar:setText(Format("%s [%d/%d] (%.1f",L(v.name), attribValue, nut.config.get("maxAttribs"), attribValue%1 * 100) .. "%)")

Issue can be clearly seen if you set any attribute to a number with a decimal. It will round up.
So if you set your attribute to 0.1. It will display as 1 with 10% progress.

**Comment by rebel1324** [comment]
sorry
