### ISSUE TITLE
Load Characters you do not own | Search offline characters inventories. 

### ISSUE THREAD

**Issue by biorisk2** [rebel1324/NutScript#102]
A command to load characters / inventories that are not owned by the administrator using the command
For example: 
/loadchar <id/name>

Also, it would be nice to be  able to search offline inventories of characters for item administration.
for example:
/openinv <id/name>

**Comment by rebel1324** [comment]
Pretty helpful management system. Will be added when I'm available.

**Comment by pmx625** [comment]
**This was added to our trello board! Thank you for your suggestion!**
