### ISSUE TITLE
If you press y and u at the same time, it opens two chats at once and you need to fixchatplz in console.

### ISSUE THREAD

**Issue by Chancerawr** [rebel1324/NutScript#108]
y and u are the default chat buttons, y for all chat, u for team chat in case you rebound some keys.

**Comment by SleepyMode** [comment]
Under review

**Comment by SleepyMode** [comment]
Hey, we have a little surprise upcoming which should fix all those sort of things as well.
I'll not close it for now, but this will not be fixed unless the update won't do the job.
