### ISSUE TITLE
Add a limit to how many items can be bought at once in business tab.

### ISSUE THREAD

**Issue by Tanoshi-Shinto** [rebel1324/NutScript#116]
i guess this is a bug and a nice suggestion would be to restrict the amount of one item a player can buy in the business tab. at the moment if  a player gets bored enough they can buy 1000+ of the same item and crash the server due to there not being a limit

**Comment by rebel1324** [comment]
Nice

**Comment by Tanoshi-Shinto** [comment]
make an auto clicker for mouse1 go into business tab and hold down purchase for a minute or so the buy then shipment it will lag then server and then if they drop all the items out if the container it will crash the server

**Comment by rebel1324** [comment]
Fixed problem by adding delay between each business purchase
