### ISSUE TITLE
Admin ESP.

### ISSUE THREAD

**Issue by TrippyNightmare** [rebel1324/NutScript#119]
Very simple request, possibly look at removing the lines stemming from players names? It just seems so clusterfucked when you hop into observer on a big server, it makes it really hard to deal with various things when you can't see where you're going, and keep getting distracted by said lines.

**Comment by rebel1324** [comment]
thanks for the feedback.
I'll fix it in short time.

**Comment by TrippyNightmare** [comment]
Blacktea, it's Trippy, Casadis already did it.

________________________________
