### ISSUE TITLE
Sandbox like features showing up in nutscript.

### ISSUE THREAD

**Issue by TheOtherAsianGuy** [rebel1324/NutScript#12]
i see killfeeds in the top right corner, names and health percentage when facing a player, and notifications of newly equipped  items on the right side of the screen.

thanks for takin' a gander.

**Comment by Chancerawr** [comment]
Put all of these into cl_hooks.lua and it should turn most of them off.

--disables kill feed
function SCHEMA:DrawDeathNotice() 
	return false
end

--disables ammo pickup notifications
function SCHEMA:HUDAmmoPickedUp() 
	return false
end

--disables weapon pickup notifications
function SCHEMA:HUDDrawPickupHistory()
	return false
end

--disables target identification (name percent health)
function SCHEMA:HUDDrawTargetID()
	return false
end

**Comment by TheOtherAsianGuy** [comment]
i also have a huge problem where PAC does not want to load with with all players @Chancerawr @rebel1324

**Comment by rebel1324** [comment]
open another issue with picTUres fd:(((

**Comment by rebel1324** [comment]
Update nutscript

2017. 5. 29. 오전 3:23에 "TheOtherAsianGuy" <notifications@github.com>님이 작성:
