### ISSUE TITLE
PAC 3 restricted to admins

### ISSUE THREAD

**Issue by lawayne** [rebel1324/NutScript#129]
Admins are the only one who can use PAC on any server with Nutscript.

**Comment by rebel1324** [comment]
This should be some kind of option

**Comment by aumkarpraja** [comment]
I can chime in with the same issue. There is no option to allow PAC for anyone else. Even admins can't actually load PACs.

**Comment by rebel1324** [comment]
Finally, it's about to be done.

**Comment by rebel1324** [comment]
Already Implemented, check "server" category
