### ISSUE TITLE
Physgun does not work for non-admins.

### ISSUE THREAD

**Issue by lawayne** [rebel1324/NutScript#130]
Non-admins cannot use the physgun to move props/items, even those spawned by themselves.

**Comment by rebel1324** [comment]
Possible Prop-protection conflict. will be investigated.

**Comment by rebel1324** [comment]
Investigation result: propprotect.lua is the only file that affects the physgun previlege. 
Delete propprotect.lua to make it work. 

If it still does not works, I suggest you to clean up prop protection addons
