### ISSUE TITLE
Updating Database.

### ISSUE THREAD

**Issue by rebel1324** [rebel1324/NutScript#132]
I will update the structure of database wrapper in 1 or 2 weeks. 

Will Add:
Relative Structure between database (won't affect older database.)
Prepared Statement for better performance.
Link to latest link to SQL Modules.

**Comment by rebel1324** [comment]
Targeted Module is MySQLoo. If there is 2017 version of tmysql, I might add support for that module.

**Comment by Heyter** [comment]
https://github.com/SuperiorServers/gm_tmysql4

**Comment by rebel1324** [comment]
Thx

**Comment by Rubberbandits** [comment]
dont add fucking tmysql4, that module is antequated garbage.
