### ISSUE TITLE
After editing some codes, set font “Malgun Gothic” is broken in some places.

### ISSUE THREAD

**Issue by Sweetnut1018** [rebel1324/NutScript#135]
I have set my server generic font to “Malgun Gothic”. But, when I reload server, editing codes, then some texts, which is written in F1 menu are replaced with default Garry’s Mod font. To solve this, I have to set the font again in settings or restart the server.

제 영어 실력이 그리 좋지 않아서 이렇게 남깁니다.
글꼴을 Malgun Gothic으로 해둔 상태에서 서버를 수정하면 F1 메뉴의 글자 등이 원래 게리모드 상태로 돌아가는 일이 발생합니다. 이를 해결하려면 설정에서 다시 Malgun Gothic으로 변경하거나 서버를 재시작해야 합니다.

**Comment by rebel1324** [comment]
Fixed
