### ISSUE TITLE
Clientside Error on Item Transfer between Player Inventories 

### ISSUE THREAD

**Issue by THE-HAVOK** [rebel1324/NutScript#142]
[ERROR] gamemodes/ww2ns/schema/derma/cl_inventory.lua:313: attempt to index local 'itemTable' (a nil value)
  1. addIcon - gamemodes/ww2ns/schema/derma/cl_inventory.lua:313
   2. unknown - gamemodes/nutscript/gamemode/core/libs/sh_item.lua:485
    3. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:155
     4. unknown - lua/includes/extensions/net.lua:32

On item transfer between two inventories owned by the same Char Inventories the error above occurs.

**Comment by rebel1324** [comment]
Let me check your code, PM/DM me. Until then, this problem is closed
