### ISSUE TITLE
Weapons look like they're raised with player model anims when sprinting.

### ISSUE THREAD

**Issue by Chancerawr** [rebel1324/NutScript#143]
https://github.com/rebel1324/NutScript/blob/1.1/gamemode/core/libs/sh_anims.lua#L265

This specific animation causes weapons to loot like they're raised when a model assigned to nut.anim.player sprints. 

Replacing it with:
[ACT_MP_RUN] = ACT_HL2MP_RUN
seems to resolve the issue.

**Comment by Johnny7A2** [comment]
tested?

**Comment by Chancerawr** [comment]
I have had this issue in the past, and someone in the support channel had this issue today. I can test it again if you want me to.

**Comment by Johnny7A2** [comment]
It's ok. Let me edit the line, thanks Chancer.
