### ISSUE TITLE
nut_dev_icon outputting wrong values

### ISSUE THREAD

**Issue by fagnig** [rebel1324/NutScript#145]
Inserting the values nut_dev_icon gives me for the top image ends up looking like the bottom image in the inventory when put into an item file.
![iconcam](https://user-images.githubusercontent.com/5938674/35390256-0cb54eba-01db-11e8-9be4-efc1be0a4307.PNG)
nut_dev_icon also outputs comma seperators in the wrong place
`ITEM.iconCam = {
	pos = Vector(-9.8999996185303, 25, 2,)
	ang = Angle(0, 270, 0,)
	fov = 70,
}
`
instead of
`ITEM.iconCam = {
	pos = Vector(-9.8999996185303, 25, 2),
	ang = Angle(0, 270, 0),
	fov = 70,
}
`
and this gives a scripterror when put into the item file.

**Comment by Sweetnut1018** [comment]
I have same issue too.

**Comment by SleepyMode** [comment]
Does it only happen with this gun?

**Comment by Sweetnut1018** [comment]
I have that issue on all of props.

**Comment by fagnig** [comment]
Same as @Sweetnut1018, all props get completely turned around when used in nut_dev_icon

**Comment by rebel1324** [comment]
Okay, let me investigate. My project is done so I'm able to fix this problem.

**Comment by rebel1324** [comment]
@fagnig I did some research- I tried with original GMOD Icon Editor, extracted value gave me same issue, I'm trying to figure out solve the problem with default GMOD icon integration.

Well, for optional use, you can add ITEM.exRender = true for Experimental IKON Rendering Library for the Icon.

**Comment by Sweetnut1018** [comment]
Is it fixed? I did update framework, but it still outputs wrong values.

**Comment by rebel1324** [comment]
no, this is not the thing I can fix with default gmod renderer. at least at this moment.
you can use ITEM.exRender = true to get it right

**Comment by Sweetnut1018** [comment]
But maybe you can fix the wrong outputting ‘ , ‘

**Comment by rebel1324** [comment]
yup
