### ISSUE TITLE
Sell Equiped Weapon Error

### ISSUE THREAD

**Issue by RonaldMacdonaldTrump** [rebel1324/NutScript#146]
If i Sell Equiped Item, then i can't see that item, can't unequip 'em.
(but if  Disconnet and connect, then is unequiped.)

영어를 못해서 추가적으로 한국어로 남기겠습니다.

만약 장착한 무기를 벤더한테 팔아넘기면, 무기가 인벤토리에서 사라져있으며, 무기는 핫바에 출력되나,해체할수 없습니다. (하지만 재접속하면 해체되어있습니다.)

**Comment by rebel1324** [comment]
문제 받았습니다

**Comment by rebel1324** [comment]
문제를 최신 Git에서 재생산 할 수 없어 문제 닫습니다
