### ISSUE TITLE
Can’t change weapons while server mounted NeuroTec addons.

### ISSUE THREAD

**Issue by Sweetnut1018** [rebel1324/NutScript#149]
Yeah, here is the link.
http://steamcommunity.com/sharedfiles/filedetails/?id=863412386&searchtext=neurotec
http://steamcommunity.com/sharedfiles/filedetails/?id=569985555&searchtext=neurotec

**Comment by rebel1324** [comment]
The new update has been pushed, update the gamemode and try again.

**Comment by Sweetnut1018** [comment]
Okay, I’ll try it. Thanks.
If I got that bug with updated framework, I’m gonna notice you here.

**Comment by rebel1324** [comment]
confirmed?

**Comment by Sweetnut1018** [comment]
Sorry, not yet.

**Comment by Sweetnut1018** [comment]
Fixed, sorry.
