### ISSUE TITLE
Mousewheel fuckery

### ISSUE THREAD

**Issue by biorisk2** [rebel1324/NutScript#155]
[ERROR] gamemodes/nutscript/plugins/wepselect.lua:150: attempt to index a nil value
  1. v - gamemodes/nutscript/plugins/wepselect.lua:150
   2. unknown - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:412

This plugin doesn't account for players who've been stripped of their weapons, please fix

**Comment by rebel1324** [comment]
got it

**Comment by rebel1324** [comment]
Is the issue still persists?
