### ISSUE TITLE
Movement falling bug

### ISSUE THREAD

**Issue by Stanstar22** [rebel1324/NutScript#161]
When falling, mash your movement keys, you will slow down a load and also you will be able to survive falling from any height as you take no fall damage.

**Comment by rebel1324** [comment]
what the hell

**Comment by rebel1324** [comment]
I can't replicate this issue, can you give me the list of addons and post the video about this issue?

**Comment by Stanstar22** [comment]
Here’s my server collection
http://steamcommunity.com/sharedfiles/filedetails/?id=1307686678
I wouldn’t expect you to go through all this, but now that I think about it, it may be something in my servers files itself. I’ll have a look later.

**Comment by rebel1324** [comment]
Reopen this issue when you get why you're getting this issue
