### ISSUE TITLE
attempt to index global 'SCHEMA' error

### ISSUE THREAD

**Issue by callum1h3** [rebel1324/NutScript#162]
So, When I join the server I tried to load it up it just has a black screen and never loads. I'll send the logs here:

[ERROR] gamemodes/nutscript/gamemode/core/derma/cl_character.lua:45: attempt to index global 'SCHEMA' (a nil value)
  1. Init - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:45
   2. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
    3. unknown - gamemodes/nutscript/gamemode/core/libs/sh_character.lua:691
     4. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:155
      5. unknown - lua/includes/extensions/net.lua:32

**Comment by rebel1324** [comment]
You tried to load "nutscript" instead of schema.
