### ISSUE TITLE
(HL2RP) "Couldn't include file 'sh_voices.lua'"

### ISSUE THREAD

**Issue by SkyArmyNinja** [rebel1324/NutScript#164]
`Couldn't include file 'sh_voices.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 17))`
I get this error on my HL2RP server every time I choose a Civil Protection character. Any help would be appreciated.

**Comment by rebel1324** [comment]
file is not valid. check the file system.
