### ISSUE TITLE
wepselect.lua errors

### ISSUE THREAD

**Issue by GreatAssassin03** [rebel1324/NutScript#173]
[ERROR] gamemodes/nutscript/plugins/wepselect.lua:150: attempt to index a nil value
  1. v - gamemodes/nutscript/plugins/wepselect.lua:150
   2. unknown - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:412

When I spawn onto a character, new or old and try to left click, it prints the error into console. When I attempt to scroll up and down to view what weapons I have, it does not show up. I also have troubles with spawning weapons, with all flags and superadmin.

I have not touched the corefiles, nor nutscript gamemode and have downloaded a clean version.
![error](https://user-images.githubusercontent.com/37892083/39396132-723278a2-4a9d-11e8-9e4d-a01b3c711bd6.PNG)

**Comment by SleepyMode** [comment]
Beta branch or normal one?

**Comment by brianhang** [comment]
Closing because this is fixed in `1.1-beta`.
