### ISSUE TITLE
Doors Not Saving

### ISSUE THREAD

**Issue by SirAlexandervonRothenburg** [rebel1324/NutScript#176]
I've recently set over 100 doors to a faction, and after 4 hours of game play a restart caused the doors to not save.  I even see the data folder containing the saved door data, but still all doors are not owned.
[doors.txt](https://github.com/rebel1324/NutScript/files/1976877/doors.txt)

**Comment by rebel1324** [comment]
is your ns 1.1 is the latest version?

**Comment by SleepyMode** [comment]
http://prntscr.com/jjeyd2
Closed
