### ISSUE TITLE
My schema broke

### ISSUE THREAD

**Issue by kiruthekiller** [rebel1324/NutScript#182]
After update, my schema fucked up and nutscript only showing "Loading" on black screen. How i can update my schema?

**Comment by rebel1324** [comment]
No error?

**Comment by rebel1324** [comment]
it seems that's not the only error. please provice EVERY ERROR you get in the console.

**Comment by kiruthekiller** [comment]
You're right, there is one more: https://pastebin.com/mUibjdXc

**Comment by rebel1324** [comment]
can you give me your screencap of that line?

This is the thing what I've got.
![image](https://user-images.githubusercontent.com/2784192/40062436-2dff467c-5896-11e8-9397-cefdd038d972.png)

**Comment by rebel1324** [comment]
Fixed
