### ISSUE TITLE
nut.item.spawn acting weirdly with regards to data

### ISSUE THREAD

**Issue by fagnig** [rebel1324/NutScript#183]
I have an issue with how the function mentioned above seems to handle data.
I have a periodic function that runs this function:
```lua
nut.item.spawn("rugermk3", position, function(item) item:printData() end, AngleRand(), {["durability"] = 30})
```
This works and data is set properly, however, if I pick up this item and use a function I've implemented (attached beneath) to add 20 durability to the item I've picked up, the next item instanced and spawned will now have 50 durability

Below is a log showing this data weirdness happening live, I pick up ID 896, call repair on it, and when 897 then spawns it has an additional 20 durability on it
![image](https://user-images.githubusercontent.com/5938674/40028226-1043bbc6-57de-11e8-8af2-4a3b64d30b16.png)

This will continue to happen and scale up, say I let the same two IDs spawn without repairing 896 between spawns, then repair 896 twice, making it have 70 durability, the next repair on 897 will now put it from 30 to 90 durability, as if the data from the last few getData & setData calls are cached

EDIT: This strange behaviour gets "reset" on lua reload, meaning it goes back to 30 durability on spawn, and then the whole scenario can begin anew

The aforementioned repair function
```lua
ITEM.functions.Repair = {
	icon = "icon16/wrench.png",
	onRun = function(item)
		local client = item.player
		local comp = client:getChar():getInv():hasItem("component")
		local cost = item.repairCost
		local money = client:getChar():hasMoney(cost*3)
		if comp and money then
			if (comp:getData("quantity", 1)) >= cost then
				local repairdata =  math.Clamp( item:getData("durability", 0)+20, 0, 100)
				item:setData("durability", repairdata)
				client:notify(item.name .. " has been repaired")
				
				comp:setData("quantity", comp:getData("quantity") - cost)
				if comp:getData("quantity") == 0 then
					comp:remove()
				end
				client:getChar():takeMoney(cost*3)
			else
				client:notify("You dont have enough components for the repair")
			end
		else		
			client:notify("You dont have enough components or money for the repair")
		end

		return false
	end,
	onCanRun = function(item)
		return !IsValid(item.entity) and !item:getData("equip") and item:getData("durability") < 100 and item:getOwner():getChar():hasFlags("T")
	end
}
```

Please let me know if there's any more info I can give you

**Comment by rebel1324** [comment]
hmmm it seems the metatable is kinda interfiered somehow..

**Comment by rebel1324** [comment]
maybe I need to get on your server. add me on the steam. https://steamcommunity.com/id/GSTM/

**Comment by Rubberbandits** [comment]
this can probably be fixed with table.Merge if its an inherent issue. according to https://github.com/rebel1324/NutScript/blob/1.1/gamemode/core/libs/sh_item.lua#L61 it outright replaces the data.

**Comment by SleepyMode** [comment]
Any updates?
