### ISSUE TITLE
Weapon raise/holster doesn't work properly (no animation)

### ISSUE THREAD

**Issue by kirukiru357** [rebel1324/NutScript#185]
I can't see any difference between raised or holstered weapon in first person. It must be turned down, but it isn't.

I am using this weapon pack: https://steamcommunity.com/sharedfiles/filedetails/?id=1315194946

Clientside code of weapon base: https://pastebin.com/nz1h70gM

**Comment by SleepyMode** [comment]
The issue sources to the addon.
Closed.
