### ISSUE TITLE
Nutscript weapon equip issue

### ISSUE THREAD

**Issue by Henry112** [rebel1324/NutScript#187]
Hello, I am having this issue with nutscript that doesn't allow me to equip weapons.

\/ Code is below \/

ITEM.name = "Raging Bull"
ITEM.desc = "A strong and powerful revolver, packs a punch!"
ITEM.model = "models/weapons/w_357.mdl"
ITEM.class = "fas2_ragingbull"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.height = 2
ITEM.iconCam = {
	ang	= Angle(-0.020070368424058, 270.40155029297, 0),
	fov	= 7.2253324508038,
	pos	= Vector(0, 200, -1)
}

Thank you for viewing and helping me I appreciate it :)

I also tried the uniqueid thing before and it didn't seem to work, I really hope this can be fixed and thanks :)

**Comment by kirukiru357** [comment]
Try to change ITEM.weaponCategory to another, "secondary" for example.

**Comment by Henry112** [comment]
tried that already, didn't work.

**Comment by kirukiru357** [comment]
Do you have latest version of NS? And this is only weapon equipped or there are others?

**Comment by Henry112** [comment]
I just updated nutscript, still nothing... and all the weapons are unequippable.

**Comment by kirukiru357** [comment]
Where your sh_weapon is? It should be in ../items/weapons/

**Comment by Henry112** [comment]
Yes it is there.

**Comment by Henry112** [comment]
Never mind I managed to fix it, the scema is was using had the folder named weapon instead of weapons, I changed it to weapons and it fixed the problem. Thank you for you help though :)
