### ISSUE TITLE
Cant move a item in your inventory more than one time.

### ISSUE THREAD

**Issue by JakeyCakey** [rebel1324/NutScript#19]
See the [THIS LINK](https://youtu.be/Jg5NSqE03eE) video, sorry for the bad music.

After moving something in your inventory for one time, it's unable to be reorganized somewhere else.

**Comment by rebel1324** [comment]
Hmm, I never experienced that.
Let me replicate it.

**Comment by Thadah** [comment]
Could reproduce when I was testing the /fallover stuff, thought it was a derma issue, but I can't confirm.

**Comment by JakeyCakey** [comment]
@Thadah I have reloaded the inventory and it still seems rather sporadic with the results. [Link Video](https://youtu.be/ndacIF4ACS0) I'm not sure if this is caused by something on my side.

**Comment by rebel1324** [comment]
Well I spent 9 weeks to find what causes inventory ghosting.
Maybe this is the thing that you need to spend some time on.
