### ISSUE TITLE
Schema name "Unknown" until first ply connects

### ISSUE THREAD

**Issue by blt950** [rebel1324/NutScript#191]
Seems after the recent restructure of how the schemas load in and order, now all servers start with "NS - Unknown" as gamemode, and this gets fixed once the first player joins.

**Comment by rebel1324** [comment]
hmm strange. let me investigate.

**Comment by brianhang** [comment]
Do you still have this issue? I can't seem to replicate it.

**Comment by brianhang** [comment]
Since the new version of NS will remove the NS prefix stuff anyways, you should probably overwrite the `GetGameDescription` hook to return the schema name in the schema with the "NS" prefix (or without).

**Comment by brianhang** [comment]
It wouldn't have to be in the framework. You could add it to the schema. Maybe the framework shouldn't really be restricting people's gamemode names.

Also, this was after switching to MySQL with the `mysqloo` module.

**Comment by blt950** [comment]
I know, I'm trying to say it doesn't work unless I put it in the framework. I've already `GetGameDescription` in sh_schema, but still it says unknown until the first player joins. If you can't reproduce it with Nut 1.1 (non-beta) and mysqloo, then that's weird - I'll start digging and debugging it, perhaps I'll figure it out. I've reinstalled multiple nutscript servers since the first post here, and I'm still struggling.

**Comment by blt950** [comment]
Ok my first digging shows following:

This is the trace from sh_schema.lua, and it's only called after first player joins the server, which fixes the issue of schema name.
```Trace:
        1: Line 32      "Trace"         lua/includes/extensions/debug.lua
        2: Line 7       "nil"           gamemodes/hl2rp/schema/sh_schema.lua
        3: Line 428     "nil"           gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua
```

sh_plugin.lua from framework at 428 is calling hooks, leading all the way back to that `nut.plugin.initialize()` which runs at `function GM:OnDatabaseLoaded()` in shared.lua. OnDatabaseLoaded() is called with `hook.Run("OnDatabaseLoaded")` in init.lua which ran under `nut.db.connect(function()` at line 23. Which leads to line 191 in sv_database.lua in nutscript who does `dbModule.connect(callback)`.

This makes sense, as once the first player joins, the console prints out message that database has connected. `dbModule.connect(callback)` is where it stops, and the callback of `nut.db.connect(` is not ran before the first player runs, that's also then `OnDatabaseLoaded` hook is run and makes the sh_plugin run the `SCHEMA:GetGameDescription` and all other hooks.

If you run `sqlite` the database connects immediately after start. mysqloo runs async, so it seems the library/bin is waiting for the player to join the server before actually connecting and trigger the callback which then loads in all plugins (and schema as it is a plugin). The reason of the schema being "Unknown" to start with is that the schema is not loaded before "OnDatabaseLoaded" is called from a successful connection which the loads schema and plugin, therefore the framework fallback on "Unknown".

**Comment by brianhang** [comment]
I see, in the `1.1-beta` branch, `nut.plugin.initialize` is called in the normal `Initialize` hook. So it's probably safe just to make the same change. If a plugin were to rely on the database connection, it should probably do the query stuff in the `OnDatabaseLoaded` hook.

**Comment by brianhang** [comment]
Can you test the changes here? https://github.com/rebel1324/NutScript/pull/254/files
