### ISSUE TITLE
Nutscript errors

### ISSUE THREAD

**Issue by Starstriker112** [rebel1324/NutScript#192]
Hi, 
whenever I load into my server I get this error:
Failed creating font 'Clear Sans Medium'!
Failed creating font 'Clear Sans Medium'!
Failed creating font 'Clear Sans Medium'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'dejavusansmono'!
Failed creating font 'TargetID'!

and I cant get past the loading screen but for some reason when I hit pause I can see the map the server is running just fine and know I have loaded in because I can hear sounds and everything.

**Comment by 54** [comment]
What branch of NutScript are you on (Chessnut's 1.1, Rebel's 1.1 or 1.1-beta)? And, what schema is this?

**Comment by Starstriker112** [comment]
Im on rebels 1.1 master and using sample schema modified to starwarsrp

**Comment by SleepyMode** [comment]
Caused by third party modifications.
Closed.
