### ISSUE TITLE
How does one change the Character Menu music?

### ISSUE THREAD

**Issue by LordPetski** [rebel1324/NutScript#195]
Hello! Im having trouble replacing the Music in the Character Menu - Could you perhaps give me a quick guide how to? I've been trying to figure it put for a long time.

**Comment by kirukiru357** [comment]
F1 > Config > "...music..." option > set to nothing(space).

**Comment by LordPetski** [comment]
But how do i change it? I have an MP3 file i want it to play instead, but i am unaware on how to ''connect'' it. Furthermore, if i do try and change the music, then it automaticly changes itself back when i change menu or just leave the menu.

**Comment by kirukiru357** [comment]
1. If you want to change music you should press Enter after editing
2. You can't use MP3. Use wav file stored somewhere in addons folder.

**Comment by Zadkielh** [comment]
1. You can use mp3s
2. The Mp3 needs to be in the sound directory of the client. Use the content folder and fastdl it for example or upload it as an addon.
3. In the config menu enter the path. So if you have it in sound/menumusic/menumusic.mp3 then in the f1 config you type menumusic/menumusic.mp3. I personally just have it in the sound folder so I can just type the sound file name directly into the config menu.

**Comment by SleepyMode** [comment]
What @Zadkielh wrote should work.
If you still experience issues, try a fresh install of our 1.1 branch.

**Comment by rebel1324** [comment]
Also please leave support comment in forum or discord.
