### ISSUE TITLE
How does one Configure Respawn time on a flag?

### ISSUE THREAD

**Issue by LordPetski** [rebel1324/NutScript#197]
Hello! I've been meddling with flags for some time now, since i wish to reconfigure the respawn time on whoever has these flags, but i am unsure how to do it. Advice or any other form of help would be appreciated. :)

**Comment by SleepyMode** [comment]
... what?

**Comment by SleepyMode** [comment]
Not yet, but you gave me an idea for something.

**Comment by LordPetski** [comment]
Why is this closed? I didn't get any form of help whatsoever >_>

**Comment by HeyBanditoz** [comment]
Issues are not a support desk.

**Comment by SleepyMode** [comment]
Refer to rebel's comment on your other issue.
