### ISSUE TITLE
Proper Documentation please?

### ISSUE THREAD

**Issue by Noname12345GER** [rebel1324/NutScript#20]
The Documentation provided is insufficient and other tutorials are featauring V1.0.

Are there any Setup guides somewhere ?

**Comment by Noname12345GER** [comment]
Sorry i was a little pissed because nothing seems to get it working. The exact problems i am having are:

**Comment by rebel1324** [comment]
I'm trying hard.
I want to explain all of NutScript but doing it alone is hard.
Also DarkRP made it's Documentation over like 5-8 years.

Anyway, Thanks for the feedback.

**Comment by Thadah** [comment]
The development of NutScript itself has revived less than a month ago after almost two years of hiatus. The wiki you are quoting has even less time.

ModernRP should be working if it's properly installed without any flaws, at least none have been reported lately.
About the animations, have you done ```nut.anim.setModelClass(model, class)``` for the models you have added?

**Comment by Noname12345GER** [comment]
I haven't. Im really looking forward to use Nutscript as I like the concept of it and it's something fresh.

But for now I unfortunately have to Stick to DarkRP.

I also like that nutscript has Advanced mechanics with would require scriptfodder today.

If you really want to make it popular you would have to implement an Whitelist and similarities to ARCBank and VCMod as Server Owners are pissed if they have to pay for Scripts.

**Comment by Thadah** [comment]
I created a wiki page explaining how to install NutScript with a schema

https://nutscript.miraheze.org/wiki/Installing_Nutscript

**Comment by Noname12345GER** [comment]
It's a beginning.

**Comment by pmx625** [comment]
Do understand that all of us do this for FREE so that users like you are able to create powerful and fun gamemodes to run on your garry's mod server.
We like to help people like you to start your servers by adding the best features to NutScript framework.

**Comment by Noname12345GER** [comment]
I am really appreciating the time work and effort you put in it. I was just sharing my thoughts.
