### ISSUE TITLE
Up-To-Date Framework and Schema not saving just about anything SQL related

### ISSUE THREAD

**Issue by 8footpartysub** [rebel1324/NutScript#202]
Characters not saving, /charsetmodel not saving, items not saving in inventory, faction transfers not saving, giving flags not saving, all after one restart following these changes. I am certain that I have never touched the SQL database files, only looked at them. So it's still on SQLite, or whatever.

Using 1.1 latest, and sample schema from 2017.

**Comment by SleepyMode** [comment]
Can't recreate
