### ISSUE TITLE
Plugin Howl Problem

### ISSUE THREAD

**Issue by russianmtf** [rebel1324/NutScript#206]
`PLUGIN.name` = "Vorti-Howl"
PLUGIN.author = "josephfra"
PLUGIN.desc = "Howling for Vorts!"

if CLIENT then
	surface.CreateFont("nut_C_Yell", {
		font = mainFont,
		size = 24,
		weight = 1000,
		antialias = true
	})
end

nut.chat.register("howl", {
	onChat = function(speaker, text)
		if (LocalPlayer():Team() == FACTION_VORT) then
		 chat.AddText(Color(77, 158, 154), nut.schema.Call("GetPlayerName", speaker, "howl", text).." howls: "..text)
		 surface.PlaySound( "vo/outland_01/intro/ol01_vortcall0"..math.random(1, 4)..".wav" )	
	    else
		 chat.AddText(Color(77, 158, 154), "A vortigaunt howls")
		 surface.PlaySound( "vo/outland_01/intro/ol01_vortcall0"..math.random(1, 4)..".wav" )
	    end
	end,
	canSay = function(speaker)
		if not (speaker:Team() == FACTION_VORT) then
			nut.util.Notify(nut.lang.Get("no_perm", speaker:Name()), speaker)

			return
		end

		return true
	end,
	font = "nut_C_Yell",
	prefix = "/howl"
})`

I get no errors but everytime I try using it gives me "Sorry, that command does not exist."             
Anything I did wrong?

**Comment by rebel1324** [comment]
There is two possibilities
1. the plugin is not loaded
2. the plugin has errors

**Comment by russianmtf** [comment]
'Command 'howl' does not have a callback, not adding!'
