### ISSUE TITLE
Leg error

### ISSUE THREAD

**Issue by RonaldMacdonaldTrump** [rebel1324/NutScript#207]
If model is not a player only model, just duck, and turn around, the error is approch...

picture : https://steamcommunity.com/sharedfiles/filedetails/?id=1447702839

**Comment by SleepyMode** [comment]
Probably an addon, can't reproduce

**Comment by yunusemregul** [comment]
its same for me too, have no addons installed instead the default

**Comment by SleepyMode** [comment]
@yunusemregul your HUD tells a different story.
Again, not an issue w/ default NS.
