### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by RonaldMacdonaldTrump** [rebel1324/NutScript#208]
the Information doesn't refresh. (If i opened it. (ex. everything except time(like a payday.)))

**Comment by pmx625** [comment]
Please be more specific. Detail what is happening and provide any errors or screenshots if you can.

**Comment by RonaldMacdonaldTrump** [comment]
https://youtu.be/zLmDaDWIgEw

"토큰" == "Token"

**Comment by RonaldMacdonaldTrump** [comment]
Ah... I was capture this video to use english,
Well, then i expect about that more, i'm talking about f1 information tab isn't refresh real-time when i quit the information tab. So,  when i make the some text-line need real-time like an health, amour...etc, this one be stumbling block.

**Comment by brianhang** [comment]
It doesn't refresh since most of the text do not change. You will need to update the label yourself like the time does here: https://github.com/rebel1324/NutScript/blob/1.1/gamemode/core/derma/cl_information.lua#L136
