### ISSUE TITLE
Kicking and banning breaks main menu.

### ISSUE THREAD

**Issue by OwenOblivi** [rebel1324/NutScript#21]
https://gyazo.com/f4dd3a071e93b605928bea7d30c4188c 
You can "return to previous menu" that isn't their.

**Comment by rebel1324** [comment]
Hmm weird.
I've banned like 40 people in one month but never happened something like this.

**Comment by rebel1324** [comment]
So this is kicking and banning character or player?

**Comment by OwenOblivi** [comment]
no, whats happening is when you kick or ban a player you get the wrong menu button. Meaning,
the "Leave" button is "return" so when you click the button you get stuck viewing a camera that over looks the map.

**Comment by SleepyMode** [comment]
I've tried it myself with a friend, the problem simply isn't there.

**Comment by Thadah** [comment]
I tried myself and I can't seem to reproduce the problem. Are there any steps you know can cause the problem?
