### ISSUE TITLE
Custom Item Support

### ISSUE THREAD

**Issue by AlyISan** [rebel1324/NutScript#217]
Potential inclusion for custom-item support as a base feature, or additional - It was my awareness that current NutScript struggles to allow this unless it was changed?

Allows for the following:
- Changing an existing items name, making a temporary unique one - or multiple.
- Ability to change said items description and perhaps title color.
- Potential to change the items additional effects 
( Maybe a single food item could be given additional statues, IE ability to heal more? )

**Comment by Rubberbandits** [comment]
This already exists.

**Comment by AlyISan** [comment]
I mean in-game editing, when an item is edited it's considered a new item and/or different one from it's original - a copy but edited.
