### ISSUE TITLE
OnLoadTables hook doesnt run for SCHEMA

### ISSUE THREAD

**Issue by yunusemregul** [rebel1324/NutScript#220]
/gamemode/core/libs/sv_database.lua line 343

I am starting nutscript with the cityrp schema, OnLoadTables hook runs for nutscript itself but not for the schema, so cityrp's some sql doesnt load. I did some debug work on that and noticed that SCHEMA is nil when that hook is getting called. Fixed it by replacing the line with; `timer.Simple(0,function() hook.Run("OnLoadTables") end)`.

**Comment by SleepyMode** [comment]
Beta branch?
