### ISSUE TITLE
Respawn bug

### ISSUE THREAD

**Issue by jasper206** [rebel1324/NutScript#239]
hey, sorry about this!
Every time a player dies, they enter a spectator mode over their dead body and it won't re spawn them. The only way to fix this is to re-join the server.
I'm really new to nutscript so go easy on me please!
many thanks for any help!

**Comment by rebel1324** [comment]
There might be some error on Death/Spawn hook. Check the console and post
the error.

2018년 11월 27일 (화) 오전 9:47, jasper206 <notifications@github.com>님이 작성:

**Comment by jasper206** [comment]
Hey, thanks for the help!
There are no errors, I've tried using different third-person mods (including a couple ones made specifically as a nutscript plugin). I've tried turning on and off perma-kill (with server restarts between them) and I've tried removing perma-kill and third-person entirely with no luck.
I know this is no help but I'm afraid it's all I know about the issue :/

**Comment by jasper206** [comment]
Found the issue, turned out to be a custom death animation from one of the addons, sorry to bother you guys!
