### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by OwenOblivi** [rebel1324/NutScript#24]
In chestnut's version their is `nut.item.createInv(w, h, id)` however it is completely gone in your build.

**Comment by Thadah** [comment]
It does exist
https://github.com/rebel1324/NutScript/blob/1.1/gamemode/core/libs/sh_item.lua line 297

```
function nut.item.createInv(w, h, id)
		local inventory = setmetatable({w = w, h = h, id = id, slots = {}, vars = {}}, nut.meta.inventory)
			nut.item.inventories[id] = inventory
			
		return inventory
end
```

**Comment by rebel1324** [comment]
https://github.com/rebel1324/NutScript/blob/1.1/gamemode/core/libs/sh_item.lua#L99

what is this
