### ISSUE TITLE
Thirdparty error

### ISSUE THREAD

**Issue by RonaldMacdonaldTrump** [rebel1324/NutScript#240]
loading doesn't end :

stack traceback:
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:187: in function '_handle'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:46: in function 'reject'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:178: in function '_handle'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:176: in function '_handle'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:37: in function 'resolve'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:112: in function <gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:111>
	[C]: in function 'pcall'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:174: in function '_handle'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:37: in function 'resolve'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:285: in function <gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:280>
	[C]: in function 'pcall'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:174: in function '_handle'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:37: in function 'resolve'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:112: in function <gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:111>
	[C]: in function 'pcall'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:174: in function '_handle'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:176: in function '_handle'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:176: in function '_handle'
	gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:66: in function <gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_deferred.lua:64>

**Comment by brianhang** [comment]
There should be some other error that shows before all of these errors. Can you upload the whole console.log file?

**Comment by RonaldMacdonaldTrump** [comment]
Not a console.log, but here's video : 
https://youtu.be/bVZdoavYvRg

**Comment by brianhang** [comment]
The first Lua error was the thing I was looking for.

Try going to [`nutscript/gamemode/core/libs/sh_item.lua`](https://github.com/rebel1324/NutScript/blob/1.1-beta/gamemode/core/libs/sh_item.lua#L152), line 152, and add `PrintTable(character.vars.inv)`. Then, show the whole console output again. It seems like an inventory loaded without an ID.

**Comment by RonaldMacdonaldTrump** [comment]
Ok, I'm remove the sv.db file, and it's fixed.

**Comment by brianhang** [comment]
Migrating inventories only works on dedicated servers, so that is probably why.
