### ISSUE TITLE
/charsetname

### ISSUE THREAD

**Issue by RonaldMacdonaldTrump** [rebel1324/NutScript#242]
Correct name, New name, Error approch.

Error message : 
[ERROR] gamemodes/nutscript/gamemode/core/util/sv_notice.lua:27: Tried to use a NULL entity!
  1. Send - [C]:-1
   2. notifyLocalized - gamemodes/nutscript/gamemode/core/util/sv_notice.lua:27
    3. onRun - gamemodes/nutscript/gamemode/core/sh_commands.lua:193
     4. run - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:156
      5. parse - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:203
       6. Run - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:225
        7. unknown - gamemodes/nutscript/plugins/chatbox/sh_plugin.lua:69
         8. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
          9. unknown - lua/includes/extensions/net.lua:32

**Comment by brianhang** [comment]
Fixed in bc94cc1b3e207a6e1c335a7d50e94edcb583980f.
