### ISSUE TITLE
Command /charsetbodygroup not working

### ISSUE THREAD

**Issue by Pilot1000** [rebel1324/NutScript#243]
The command /charsetbodygroup always returns a nil value for its second argument, thus making it impossible to change anyone's bodygroup.

https://github.com/rebel1324/NutScript/blob/c84ed54f32052416dcc8b0fc86d82f3ea71ceac6/gamemode/core/sh_commands.lua#L165

**Comment by BizLight** [comment]
How are you doing it? Does your character model have bodygroups? It should be /charsetbodygroup name bodygroupname value

**Comment by Pilot1000** [comment]
It does have bodygroups, I'll show you with a video attached below
[Bodygroup Issue.zip](https://github.com/rebel1324/NutScript/files/2658631/Bodygroup.Issue.zip)

**Comment by brianhang** [comment]
But how are you using the command?

**Comment by Pilot1000** [comment]
What do you mean, "how" am I using the command?
My model has bodygroups, and I do

/charsetbodygroup "name" "skin" "1"

**Comment by brianhang** [comment]
You could try running the following command in the server console:
```lua
lua_run PrintTable(Entity(1):GetBodyGroups())
```
to see what the name is. I think the name might have to be exact, which is possibly why it isn't working. The command assumes you're the only player on the server.

**Comment by BizLight** [comment]
Did you seriously just use ""? Also you used skin which is not a bodygroup rather it uses /charsetskin charname skin value . Without the ""'s

**Comment by BizLight** [comment]
The only thing you need /charsetbodygroup  for is the gloves because those are actual bodygroups from what I see you wanted to change. so it will be /charsetbodygroup yes gloves 1

**Comment by BizLight** [comment]
And for the skin you will use /charsetskin yes skin 2

**Comment by BizLight** [comment]
The torso will be the same except it's /charsetbodygroup yes torso 2

**Comment by brianhang** [comment]
`/command yes` and `/command "yes"` are the same.

**Comment by brianhang** [comment]
I believe you just have the bodygroup name wrong. 
![image](https://user-images.githubusercontent.com/19870477/49689936-a7849300-fadd-11e8-964d-fddaa1a9d73c.png)

I'm closing this since this seems like a non-issue.
