### ISSUE TITLE
Stamina plugin

### ISSUE THREAD

**Issue by RonaldMacdonaldTrump** [rebel1324/NutScript#244]
When i hold sprint key, Stamina is keep drain.
Even i don't press the move key.

**Comment by BizLight** [comment]
That's because it thinks you are sprinting because you are holding the sprint key.

**Comment by brianhang** [comment]
I tried switching to [Player.IsSprinting](http://wiki.garrysmod.com/page/Player/IsSprinting) since it was less expensive, but it seems to only check if the sprint key is being held down.
