### ISSUE TITLE
[1.1 beta] PAC3 Integration Issues

### ISSUE THREAD

**Issue by Pilot1000** [rebel1324/NutScript#246]
Button to use PAC doesn't show anymore in the context menu.
Also, PAC3 now shows clientside model.
![h1os4pc](https://user-images.githubusercontent.com/3075268/49702807-bbf28980-fbca-11e8-988f-d02348ad7c60.jpg)

**Comment by brianhang** [comment]
Fixed by d38f47fc90e537940f5ad76eaa74ab7c20ce26bd
