### ISSUE TITLE
Double persisting in NS 1.1 beta

### ISSUE THREAD

**Issue by Pilot1000** [rebel1324/NutScript#252]
**Problem:**
Props are persisted twice when the server restarts and thus when the server opens up again twice props are in the exact same location.

**Steps to reproduce double persisting props when the server restarts:**
Don't define sbox_persist at all in server.cfg or define as "ns_<schemaname>" in server.cfg

**One temporary solution:**
Defining sbox_persist as "" fixes double loading but stops new props from persisting

**Comment by brianhang** [comment]
I can't seem to replicate this using the steps to reproduce the issue.
[2018-12-12_09-17-30.zip](https://github.com/rebel1324/NutScript/files/2672834/2018-12-12_09-17-30.zip)

**Comment by Pilot1000** [comment]
What was your server.cfg like in this video? Did you have sbox_persist set to anything?

**Comment by brianhang** [comment]
My server.cfg file is blank.
