### ISSUE TITLE
Damage Error?

### ISSUE THREAD

**Issue by RonaldMacdonaldTrump** [rebel1324/NutScript#261]
When i shoot the bullet other people, it kills people one bullet,

Scale is 4, and Bullet damage is 13~15, and result is 273, WTF?

**Comment by RonaldMacdonaldTrump** [comment]
It looks Damage scales are set like this : 
damage scale = 3 * Value for set scale

**Comment by brianhang** [comment]
Damages are scaled by the `dmgScale`, `dmgScaleHead`, and `dmgScaleLimb` configs. If the config values do not match, then it is most likely the result some other addon you have,
