### ISSUE TITLE
[1.1 beta] Backpacks Disappearing From Inventory

### ISSUE THREAD

**Issue by Pilot1000** [rebel1324/NutScript#269]
Difficult to reproduce. Sometimes when moving backpacks around in your inventory or generally working with it, it'll disappear from the inventory completely, perhaps deleting itself somehow by breaking. Not sure how to check if an item suddenly breaks. Maybe there's something can be added to report why an item gets deleted.

**Comment by Pilot1000** [comment]
I couldn't figure out how to reproduce backpacks disappearing, but I figured out how to reproduce items getting stuck in your backpack:
get 2 bags, have atleast 1 thing in both, disconnect from server, and reconnect and when you come back your items should be stuck.

**Comment by brianhang** [comment]
Closing since this seems to be fixed by a4ddf9969c5bd8b7cfd0441e12ddf51a4949ce2f and a4920493a373392941f2db3af103ad01b9fb5405.
