### ISSUE TITLE
[1.1 beta] Vendor bug

### ISSUE THREAD

**Issue by RonaldMacdonaldTrump** [rebel1324/NutScript#281]
When i buy item from vendor, inventory get initialize and there's only leave bought item.

And it print this at console :

* INSERT INTO nut_items (_y, _x, _data, _quantity, _uniqueID, _invID) VALUES (2, 1, '[]', 1, 'rebel_armor', 38)
table nut_items has no column named _quantity
[LOG] asdfasdfas has bought a John Doe from rebel_armor.

**Comment by brianhang** [comment]
Wiping the database isn't a good fix. @rebel1324 , you should add an `ALTER TABLE` query to add the column so people don't lose data when updating. See [this code](https://github.com/brianhang/NutScript/blob/1.1-beta/gamemode/core/hooks/sv_hooks.lua#L674).
