### ISSUE TITLE
SQLite.lua not found

### ISSUE THREAD

**Issue by AaronHughes** [rebel1324/NutScript#286]
I am receiving the error: 
Couln't include file 'includes/modules/sqlite.lua'  (File not found) (@gamemodes/nutscript/gamemode/libs/sv_database.lua (line 10))

I cannot play on my server without the db being made.

**Comment by SleepyMode** [comment]
What sort of Nutscript version did you even install? Holy shit.
Install the latest and try again.

**Comment by AaronHughes** [comment]
I resolved the issue with switching to a mysql database. However, I get the following error when I did that.
01/26/2019 - 22:09:42: Lua Error: gamemodes/nutscript/gamemode/libs/external/sv_mysql.lua:406: attempt to call method 'status' (a nil value)

**Comment by AaronHughes** [comment]
I'm sorry, Helix?

**Comment by SleepyMode** [comment]
Fix the schema.
We no longer support old versions.
