### ISSUE TITLE
Whitelist does not save

### ISSUE THREAD

**Issue by PaXo0** [rebel1324/NutScript#288]
Hello when i whitelist my character to the faction "Security LT" and i go back to create my character again it still does not show that faction upon the whitelist what should i do?

**Comment by SleepyMode** [comment]
Try installing the latest version.
Worked fine for me just the other day...

**Comment by PaXo0** [comment]
I just downloaded it like 30 mins ago put a few factions on all of them work apart from that one whitelisted faction (that does not show up after /plywhitelist)

**Comment by SleepyMode** [comment]
Are you sure you mean FACTIONS and not CLASSES?
Seems odd to use a faction for each rank.

**Comment by LukeTheDamnBrit** [comment]
> 
> 
> I just downloaded it like 30 mins ago put a few factions on all of them work apart from that one whitelisted faction (that does not show up after /plywhitelist)

Post your faction .lua file for your custom faction.

**Comment by PaXo0** [comment]
I'm using factions instead of classes (partly cuz i don't know how to use them properly) but also because i need to set custom models ect and people be able to edit their own models within the char creation

**Comment by LukeTheDamnBrit** [comment]
> 
> 
> I'm using factions instead of classes (partly cuz i don't know how to use them properly) but also because i need to set custom models ect and people be able to edit their own models within the char creation

Do you have your "Security LT" faction, scripted as an sh_(faction name).lua file in your gamemodes/(schema name)/schema/factions directory?

**Comment by PaXo0** [comment]
Yeah all has the same name apart from the SH_ which is sh_securityLieutenant

**Comment by SleepyMode** [comment]
> I'm using factions instead of classes (partly cuz i don't know how to use them properly) but also because i need to set custom models ect and people be able to edit their own models within the char creation

Classes remain preferable and the models thing is just about one of the easiest to do.
Take a look at Chessnut's HL2RP schema as an example.

Also, that guy's right, post your faction file's content here.

**Comment by LukeTheDamnBrit** [comment]
> 
> 
> Yeah all has the same name apart from the SH_ which is sh_securityLieutenant

Mind copy + pasting your code into the comments here for me to have a look at?

**Comment by PaXo0** [comment]
`FACTION.name = "Security Lieutenant"
FACTION.desc = "Security Lieutenant"
FACTION.color = Color(25, 30, 180)
FACTION.isDefault = false
FACTION.limit = 2
FACTION.models = {
	"models/player/humans/class_scientist/class_securety/class_securety_2.mdl",
}
FACTION.pay = 90
FACTION.isGloballyRecognized = true

FACTION_SECURITYLIEUTENANT = FACTION.index
`

**Comment by SleepyMode** [comment]
Do you get any notification when using /plywhitelist?
Perhaps a console error even?

**Comment by PaXo0** [comment]
Nope all I get is this (using 1-1 beta with sample for more info/context)
`[LOG] Paxo Jefferson used '/plywhitelist Paxo "Security LT"'
[LOG] Paxo Jefferson used '/plywhitelist Paxo "Security Li"'
[LOG] Paxo Jefferson used '/plywhitelist Paxo "Security Li"'
[LOG] Paxo Jefferson used '/plywhitelist Paxo "Junior"'
[LOG] Paxo Jefferson used '/plyunwhitelist Paxo "Junior"'
[LOG] Paxo Jefferson used '/beclass LT'
[LOG] Paxo Jefferson used '/plyunwhitelist Paxo "Security Li"'
[LOG] Paxo Jefferson used '/plywhitelist Paxo "Security Li"'`

**Comment by SleepyMode** [comment]
Any errors prior?

**Comment by PaXo0** [comment]
None what so ever idk why im using SQLite btw

**Comment by SleepyMode** [comment]
My bad, on phone :|

**Comment by SleepyMode** [comment]
Not a database issue if you're not getting any notification either.
Are you running dedicated?

**Comment by LukeTheDamnBrit** [comment]
It might be having trouble calling the faction name. I'm going to have a go on my test server with it. Also make sure you're-... ah you're using SQLite. However I doubt it could be a database issue

**Comment by LukeTheDamnBrit** [comment]
What Sleepy said ^^^^

**Comment by PaXo0** [comment]
Yeah im running dedicated (latest version)

**Comment by LukeTheDamnBrit** [comment]
It works. So go in game and try doing the command /plywhitelist (CHARACTER name / Sorry) Security Lieutenant
Which is the full name of the faction, which it calls when trying to whitelist.

**Comment by PaXo0** [comment]
Ill send you a YT video link in a sec showing the issue in full it will take a sec to upload

**Comment by LukeTheDamnBrit** [comment]
Yeah, I copied your script into a fresh sh_ and named the file sh_securitylieutenant as you have. In game, I loaded my character "Blake" and emitted the following command:
/plywhitelist Blake Security Lieutenant
And it had successfully whitelisted; I am able to create and use the character, even after leaving the game and even restarting the server. (Just to be double sure)

But yeah, sure, send us over the video anyway so we can get a good look at what could be causing it.

**Comment by PaXo0** [comment]
Heres the link sry for low quality it might get better when YT does it's thing

https://www.youtube.com/watch?v=ZE_JzC7rlJU&feature=youtu.be

**Comment by SleepyMode** [comment]
Shooting in the dark but I just figured the capital L in sh_securityLieutenant.lua could be problematic in some operating systems.
Try renaming it.

**Comment by PaXo0** [comment]
Sure will do

**Comment by PaXo0** [comment]
Ok i have found the issue i don't know why this is the case i have restarted the server and renamed the sh file to all lower cases it now works - thx for help all although still a mystery why it would cause that!

**Comment by LukeTheDamnBrit** [comment]
The uppercase! An accursed entity that causes all sorts of problems for coders!
Cool. Glad you fixed it. - A brief explanation is that NS calls the basic text of files. Doesn't recognize caps in names. So best just look out for them next time!

**Comment by PaXo0** [comment]
TY!!
