### ISSUE TITLE
Inventory not saving.

### ISSUE THREAD

**Issue by tomasalves8** [rebel1324/NutScript#291]
Switched from 1.1 to 1.1 Beta, and inventories don't save.

**Comment by SleepyMode** [comment]
Any errors in console?
Maybe anything to do with the database?

**Comment by tomasalves8** [comment]
What should i look for in console?

**Comment by SleepyMode** [comment]
Anything suspicious.

**Comment by tomasalves8** [comment]
* SELECT _itemID, _uniqueID, _data, _x, _y, _quantity FROM nut_items WHERE _invID = 281
no such column: _quantity

**Comment by SleepyMode** [comment]
You need to wipe your database or use ALTER TABLE to add the column.

**Comment by SleepyMode** [comment]
https://github.com/rebel1324/NutScript/issues/281

**Comment by tomasalves8** [comment]
What datatype for that colunm?

**Comment by SleepyMode** [comment]
Take a look at the database module.

**Comment by tomasalves8** [comment]
Copy, Thx for the help

**Comment by tomasalves8** [comment]
Fixed
