### ISSUE TITLE
Font Size is too small.

### ISSUE THREAD

**Issue by BizLight** [rebel1324/NutScript#299]
As the title says the font size is too small to even be able to read it. If you could help me out with this  it would be great. Thanks in advance. 
![4000_screenshots_20190224100717_1](https://user-images.githubusercontent.com/29734480/53297011-ac74fb00-381f-11e9-8ccb-97b9131d7280.jpg)
Here's the font link:
[https://www.dafont.com/amazstalker.font](url)

**Comment by rebel1324** [comment]
Maybe it’s related with ehh Font? Try differnet fonts


Windows 10용 메일에서 보냄

보낸 사람: BizLight
보낸 날짜: 2019년 2월 24일 일요일 오후 5:34
받는 사람: rebel1324/NutScript
참조: Subscribed
제목: [rebel1324/NutScript] Font Size is too small. (#299)

As the title says the font size is too small to even be able to read it. If you could help me out with this it would be great. Thanks in advance.

Here's the font link:
https://www.dafont.com/amazstalker.font

**Comment by BizLight** [comment]
Other fonts work fine I'm trying to resize it if it's possible. It works fine in the character menu

**Comment by chadreed93** [comment]
Some fonts are weird with source, I would try another font for certain text.
