### ISSUE TITLE
plytransfer and vendor broke

### ISSUE THREAD

**Issue by FalconsDBlock** [rebel1324/NutScript#30]
All of a sudden after a few addon changes and item/weapon additions I go to use vendor and get this when I buy something:

 
[ERROR] gamemodes/asgsw/plugins/vendor/sh_plugin.lua:307: attempt to call global 'L' (a table value)
  1. unknown - gamemodes/asgsw/plugins/vendor/sh_plugin.lua:307
   2. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
    3. unknown - lua/includes/extensions/net.lua:32

Then I try to use plytransfer and get an even bigger error like this: 

 
[ERROR] gamemodes/nutscript/gamemode/core/sh_commands.lua:658: attempt to call global 'L' (a table value)
  1. onRun - gamemodes/nutscript/gamemode/core/sh_commands.lua:658
   2. run - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:159
    3. parse - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:204
     4. Run - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:248
      5. unknown - gamemodes/asgsw/plugins/chatbox/sh_plugin.lua:69
       6. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
        7. unknown - lua/includes/extensions/net.lua:32

Anyone know where I can fix this? I've reverted a lot of stuff and for some reason it's still like this so I need to go in a file and change something. I just don't know where.

**Comment by rebel1324** [comment]
Update nutscript
And check your item and faction name

2017. 6. 9. 오전 10:11에 "FalconsDBlock" <notifications@github.com>님이 작성:

**Comment by FalconsDBlock** [comment]
Nutscript is 1.1
I've pulled each folder out one by one to see what  was causing it, nothing in the schema or nutscript core folder is causing it.

If you have any type of update let me know

**Comment by pmx625** [comment]
@FalconsDBlock Try running a fresh NutScript 1.1 version with a schema like HL2RP. See if it works. If it does it means your NutScript 1.1 installation is not working properly.

**Comment by Thadah** [comment]
@FalconsDBlock Any update on this?
