### ISSUE TITLE
Bodygroup Two Words

### ISSUE THREAD

**Issue by HmmmmmDaniel** [rebel1324/NutScript#302]
I have been having an issue where I would have bodygroups on a model but I cannot use the /charsetbodygroup command because the bodygroup is two words (Body Rank). Can you please show me the correct way if at all? Thank You.

**Comment by chadreed93** [comment]
Try using parenthesis /charsetbodygroup "body group" or try using numbers to define it just like how lua defines it, so like /charsetbodygroup 0 1. 
Reference: https://wiki.garrysmod.com/page/Entity/SetBodygroup
