### ISSUE TITLE
Unable to assign weapons to a faction or class.

### ISSUE THREAD

**Issue by arinehart911** [rebel1324/NutScript#303]
Hey there, recently I've been trying to set up some factions and classes to spawn with certain firearms. It doesn't work, however. I've tried using FACTION.weapons and CLASS.weapons to no avail, and I set the ITEM.classes in the weapon file to see if that would work too. That didn't work either. I'm really lost at this point, any help would be appreciated.

NOTE: Players don't spawn with hands or keys either, if that may be something related to it.

**Comment by BizLight** [comment]
That's not how you do it nerd. 
FACTION.weapons = {"..."}

**Comment by SleepyMode** [comment]
@BizLight originally answered the question but I've hidden his comment as it was rather rude.

The correct way to do this is:
```lua
FACTION.weapons = {"weapon_1", "weapon_2", "weapon_3"}
```
