### ISSUE TITLE
Use player animations instead of NPC animations

### ISSUE THREAD

**Issue by Iway8** [rebel1324/NutScript#308]
Hello,

I want to use player animations instead of NPC animations. But anyway what I'm changing, the animations are still the same or change for T-pose 

I tried to use this 
nut.anim.setModelClass("models/dpfilms/metropolice/urban_police.mdl", "player")

But it seems that it doesn't work. It creates a script error or a T-pose models.

**Comment by BizLight** [comment]
Hello,

It seems you are trying to use non-existing animations from the model. The one you are trying to use has npc animations. Please use the playermodel one.

Thank you and have a nice day.

**Comment by Iway8** [comment]
Thanks for answering. I tried to use a playermodel instead of a model but it doesn’t work at all. There is the same problem

**Comment by BizLight** [comment]
Send me the code you wrote :)

**Comment by Iway8** [comment]
SCHEMA.rankModels = {
    ["RCT"] = "models/dpfilms/metropolice/playermodels/pm_urban_police.mdl",
    ["i5"] = "models/dpfilms/metropolice/playermodels/pm_24nebcop.mdl",
    ["i4"] = "models/dpfilms/metropolice/playermodels/pm_black_police.mdl",
    ["i3"] = "models/dpfilms/metropolice/playermodels/pm_rogue_police.mdl",
    ["i2"] = "models/dpfilms/metropolice/playermodels/pm_police_bt.mdl",
    ["i1"] = "models/dpfilms/metropolice/playermodels/pm_elite_police.mdl",
    ["EpU"] = "models/dpfilms/metropolice/rtb_police.mdl",
    ["OfC"] = "models/dpfilms/metropolice/blacop.mdl",
    ["CmD"] = "models/dpfilms/metropolice/phoenix_police.mdl",
    ["SCN"] = "models/combine_scanner.mdl",
    ["CLAW.SCN"] = "models/shield_scanner.mdl"
}

I didn't touch to EpU, OfC and CmD.

**Comment by BizLight** [comment]
I see. You didn't properly set animations. 
nut.anim.setModelClass("model", "player")
Place that in sh_anims.lua (Nutscript > Gamemode > Core > Libs)
You replace model with the model path, you have to do it for each one.
Otherwise, if you want to use the npc models use:
nut.anim.setModelClass("model", "metropolice")
With these, you use the other npc models, not the playermodels. Enjoy :)
