### ISSUE TITLE
Talking icon still showing for players you can't hear

### ISSUE THREAD

**Issue by Thadah** [rebel1324/NutScript#31]
Talking icon still shows up even though you are far enough to not be able to hear them anymore.

**Comment by rebel1324** [comment]
The issue still consists?

**Comment by Thadah** [comment]
I haven't tested it since, but no modifications have been made, so I suppose it's still there

**Comment by biorisk2** [comment]
The commit I pushed forever ago fixed the box on the bottom right from showing up at inaudible distance, I am unsure if you mean that or the yellow speaker icon.

**Comment by Thadah** [comment]
Then it must be fixed because I was talking about the box. Thanks for notifying it.
