### ISSUE TITLE
Issue with models

### ISSUE THREAD

**Issue by BizLight** [rebel1324/NutScript#311]
Heya!
I have an issue with some playermodels as in it only t-poses and it doesn't matter if I use nut.animSetClass("model","class") it keeps t-posing. The model has both npc and player animations (although, in sandbox for example, it uses the playermodel animations). Could you please help me? Thanks in advance.
![4000_screenshots_20190519215451_1](https://user-images.githubusercontent.com/29734480/58039080-012fc580-7b32-11e9-88aa-83fb77719a6b.jpg)

**Comment by TovarischPootis** [comment]
Same as #328
