### ISSUE TITLE
Clip1() in nshud

### ISSUE THREAD

**Issue by dartunian** [rebel1324/NutScript#316]
https://github.com/rebel1324/NutScript/blob/62dfb37cd155f3766d6ad6acf1bcdc3b3f493794/plugins/nshud/sh_plugin.lua#L44

from
`if (weapon.GetClass(weapon) ~= "weapon_slam" and clip > 0 or count > 0) then`
to
`if (clip and weapon.GetClass(weapon) ~= "weapon_slam" and clip > 0 or count > 0) then`

if `Clip1()` is not active, script errors

**Comment by SleepyMode** [comment]
Consider opening a pull request.
