### ISSUE TITLE
Male NPC Animations are not working properly

### ISSUE THREAD

**Issue by InfinityTech2** [rebel1324/NutScript#317]
![20190901104429_1](https://user-images.githubusercontent.com/54776664/64080147-b895b580-cca5-11e9-9e99-7a94aea7e995.jpg)
![20190901104437_1](https://user-images.githubusercontent.com/54776664/64080148-ba5f7900-cca5-11e9-9eaa-536af16baeb3.jpg)
![20190901104434_1](https://user-images.githubusercontent.com/54776664/64080151-bc293c80-cca5-11e9-8b47-cf69190dd83f.jpg)

The standing and walking animations with weapons for standard male npcs seem to be not working properly. I am using a base nutscript file with mods that don't effect animations. Any fixes?

**Comment by Chancerawr** [comment]
It might be a clientside issue. My recommendation would be to verify your game files or possibly reinstall gmod. Nutscript by itself (to my knowledge) doesn't do anything to the regular citizen NPCs or their animations. 

The only animations NS will affect are usually the players' animations.

**Comment by InfinityTech2** [comment]
Other people can see it too, this was on a server

**Comment by InfinityTech2** [comment]
Models using the female animations are working completely fine though, I can send you a link to the content pack I'm using for my server if that may help
