### ISSUE TITLE
Item Spawner Issue

### ISSUE THREAD

**Issue by Devasta1** [rebel1324/NutScript#321]
Whenever it spawns ammo, it'll only spawn a "single instance" of the item, and the ammo will only have 1 bullet to load.

Ammo Item: 
ITEM.name = "7.62mm Ammo"
ITEM.model = "models/items/ammo/ammo_762.mdl"
ITEM.ammo = "ar2" // type of the ammo
ITEM.ammoAmount = 30 // amount of the ammo
ITEM.ammoDesc = "A box that contains 7.62x39mm Soviet rounds."
ITEM.category = "Ammunition"
ITEM.flag = "y"

Any idea why it would only give one bullet?

**Comment by Rubberbandits** [comment]
Are you using 1.1 or 1.1-beta?

**Comment by Devasta1** [comment]
1,1 beta

**Comment by Rubberbandits** [comment]
The format has changed. Use 

`ITEM.name = "Ammo Base"
ITEM.model = "models/Items/BoxSRounds.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.isStackable = true
ITEM.maxQuantity = 45
ITEM.ammo = "pistol" -- type of the ammo
ITEM.desc = "A Box that contains %s of Pistol Ammo"
ITEM.category = "Ammunition"`

**Comment by Devasta1** [comment]
Thank you!
