### ISSUE TITLE
Unknown table before player words

### ISSUE THREAD

**Issue by Arrow9867** [rebel1324/NutScript#323]
![ddddddddddddddd](https://user-images.githubusercontent.com/28177586/66914284-013edd80-f05e-11e9-947b-33deb40f0e43.PNG)
This happens on my server, using a modified sample schema and NS 1.1 beta. There are no errors related to this in console, tried removing all content, reinstalling blank schema and framework and still no fix. Also I can't replicate this on my local dedicated server, even with the same files.

It could be related to chat box colour, as changing the config for the chat colour changes the values of the 'table:'.

**Comment by community85** [comment]
This has happened on our servers as well. Any fix?
