### ISSUE TITLE
nut_item entity does not take damage ?

### ISSUE THREAD

**Issue by MrSylar59** [rebel1324/NutScript#33]
Okay so, I wanted to allow a player to destroy an item on the ground by dealing damage to it. Therefore I tried to add the ENT:OnTakeDamage(dmg) directly to the item and as it didn't work, I tried making a plugin with the hook PLUGIN:EntityTakeDamage(ent, dmg).

Sadly, I have no result:

```
function PLUGIN:EntityTakeDamage(ent, dmg) 
		print("test")
end
```

This code outputs "test" in the console whenever I beat an entity (even nutscript's ones) but it does nothing when I try it on an item. Any clue/idea to help me out ?

**Comment by rebel1324** [comment]
Wait for it
I'll fix it

**Comment by MrSylar59** [comment]
Any news about that particular problem ? I still haven't managed to fix it on my side and it's the last thing I would like to implement on my server ^^'

**Comment by SleepyMode** [comment]
Hey, there is an issue with this, please stand by as we are trying to find a fix.

**Comment by MrSylar59** [comment]
Okay, tell if you happen to find anything, I'll keep searching on my own too and let you know if I can find something.
