### ISSUE TITLE
Gamemode not detected

### ISSUE THREAD

**Issue by Maxxx0000** [rebel1324/NutScript#330]
Whenever I drop my nutscript gamemode "swsrp" into my gamemodes folder it is not a selectable gamemode in the menu, i also tried it on my friends deticated server and it did not work. Screenshots attatched below:
![image](https://user-images.githubusercontent.com/48693688/75629524-a6f08480-5bda-11ea-9722-ae8a25554815.png)
![image](https://user-images.githubusercontent.com/48693688/75629534-b66fcd80-5bda-11ea-8e97-4bafb4a7bd3f.png)

**Comment by SleepyMode** [comment]
https://wiki.garrysmod.com/page/Gamemode_Creation

**Comment by chadreed93** [comment]
this is not a nutscript issue

**Comment by Zoephix** [comment]
🤦‍♂️

**Comment by TovarischPootis** [comment]
https://nutscript.miraheze.org/wiki/Developing_Schema
