### ISSUE TITLE
1.1-Beta Text Color Issue

### ISSUE THREAD

**Issue by ts-co** [rebel1324/NutScript#334]
It seems that config colors are not coming in as actual Colors and instead are showing up in-game as their printed table id. My hotfix was to do

`
Color(nut.config.get("color").r, nut.config.get("color").g, nut.config.get("color").b)
`

But there's probably a cleaner way of fixing this.

**Comment by Zoephix** [comment]
It's probably because you're doing a color inside of a color right now, nut.config.get("color") is already defined as color.

**Comment by ts-co** [comment]
What I did is a working hotfix. nut.config.get("color") which is default NutScript is being read as a table instead of a color for some reason and is outputting its table id.

**Comment by TovarischPootis** [comment]
This issue has been fixed
