### ISSUE TITLE
Multiple factions on a door

### ISSUE THREAD

**Issue by Cannon331** [rebel1324/NutScript#335]
Is there a way to have multiple factions on a door? Is there coding involved to do this?

(Sorry if this is the wrong place for this)

**Comment by masonmanley** [comment]
Wrong place. Ask on Discord.

**Comment by TovarischPootis** [comment]
This feature is offered by a member of the NS discord. Suggest to close the issue

**Comment by theuniquejohnny** [comment]
Locking - This is not an issue
If you want to buy that feature contact in discord: Zoephix#3530
