### ISSUE TITLE
NS 1.1B Cant Equip Weapons

### ISSUE THREAD

**Issue by JayyKush** [rebel1324/NutScript#339]
No matter what I do no matter the code it wont work here is the basic of what I am using.

ITEM.name = "AK-47"
ITEM.desc = "A Russian made carbine released in one of the first widely adopted intermediate cartridges. The ammunition is hard-hitting, and the recoil controllable when fired in semi-automatic. Short, controlled bursts must be utilized to maintain accuracy at ranges greater than 50m."
ITEM.model = "models/weapons/tfa_w_ak47_tfa.mdl"
ITEM.class = "tfa_ak47"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.price = 0
ITEM.height = 2
ITEM.flag = "v"
ITEM.category = "Weapons - Rifles"
ITEM.iconCam = {
	pos = Vector(-200, 11.5, 2.5),
	ang = Angle(0, -0, 7),
	fov = 12,
}

I have the model pack but no matter what I cannot equip it from the F1 menu as the option just does not show

**Comment by baratoxis** [comment]
Hello! 
I advice you to join the official discord for faster support: https://discord.gg/PuYqQ9F

Is the file where it is saved at under gamemodename/schema/items/weapons/sh_* being the * an unique id?

Looking to hear from you, 

Barata

**Comment by JayyKush** [comment]
> 
> 
> Hello!
> I advice you to join the official discord for faster support: https://discord.gg/PuYqQ9F
> 
> Is the file where it is saved at under gamemodename/schema/items/weapons/sh_* being the * an unique id?
> 
> Looking to hear from you,
> 
> Barata

Hello thank you but I realised in my own stupidity I did not transfer the sh_weapons file, i will be closing this now
