### ISSUE TITLE
Factions with bodygroups

### ISSUE THREAD

**Issue by JohnBiggums** [rebel1324/NutScript#35]
I'm wondering how I can make a faction as a whole all spawn with a certain bodygroup by default, unless an admin changes it.

**Comment by SleepyMode** [comment]
SCHEMA:OnSpawn( ply )
PLUGIN:OnSpawn( ply )

simply get their faction and set up whatever you need.

**Comment by rebel1324** [comment]
SCHEMA:PlayerLoadout(client) is the right choice mate

**Comment by SleepyMode** [comment]
Both will work, either way.
