### ISSUE TITLE
Using wOS causes your character model to sway

### ISSUE THREAD

**Issue by StaticXNation** [rebel1324/NutScript#36]
As the title says, when you're using the wOS animations (http://steamcommunity.com/sharedfiles/filedetails/?id=757604550 and http://steamcommunity.com/sharedfiles/filedetails/?id=848953359) your character model sways when idle like so https://gyazo.com/a355e5f11aa7cfec40d1cf188f7123c0

**Comment by Thadah** [comment]
That's kinda cool, but I understand why you want it fixed

**Comment by Thadah** [comment]
Is the issue still happening?

**Comment by StaticXNation** [comment]
Sorry, but forgot to update this. This isn't a nutscript issue. It's due to one of animations within wiltOS overriting the idle animations.

**Comment by rebel1324** [comment]
It doesn't mean that's not a problem. 
Let's go with Sequence Based instead of Activity Based.

**Comment by rebel1324** [comment]
Yeah it seems it overwrites everything. I need to talk about wOS author about this issue.
If I can lol
