### ISSUE TITLE
Change in database causing migration to break

### ISSUE THREAD

**Issue by Rubberbandits** [rebel1324/NutScript#364]
https://github.com/rebel1324/NutScript/blob/d92c761459d7495d7dec7c2837b3575513f8dd55/gamemode/core/libs/sv_database.lua#L361

This change in the column data type from INT(11) UNSIGNED to INT(12) breaks foreign key constraints that nut_invdata uses. Alongside that, the migration script doesn't check if the next inventory it's going to try to migrate is even a valid row in the database, causing a script error at the end of inventory migration. This doesn't break the migration, but requires a server restart for anyone to connect.

**Comment by its-johnny** [comment]
Ty Rusty
