### ISSUE TITLE
Error when purchasing item from vendor

### ISSUE THREAD

**Issue by StaticXNation** [rebel1324/NutScript#37]
I'm trying to make an item that replaces your model when you equip it, but everytime I try to purchase it from the vendor, I get an error. Here is the error and the code for my item https://pastebin.com/55fKwryb

Tested with version of the vendor before the update 7 days ago and the version of the vendor on chessnuts nutscript version.

EDIT: Error happens with any item you try to buy in the vendor.
EDIT2: Forgot to mention that when you try to purchase the item and you get the error, the item doesn't actually get purchased. Just nothing happens.

**Comment by SleepyMode** [comment]
Is the issue still present?

**Comment by StaticXNation** [comment]
Yes. Updated nutscript and the issue is still happening

[ERROR] gamemodes/nutscript/plugins/vendor/sh_plugin.lua:307: attempt to call global 'L' (a table value)
  1. unknown - gamemodes/nutscript/plugins/vendor/sh_plugin.lua:307
   2. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
    3. unknown - lua/includes/extensions/net.lua:32


[ERROR] gamemodes/nutscript/plugins/vendor/sh_plugin.lua:307: attempt to call global 'L' (a table value)
  1. unknown - gamemodes/nutscript/plugins/vendor/sh_plugin.lua:307
   2. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
    3. unknown - lua/includes/extensions/net.lua:32

**Comment by Thadah** [comment]
Could you please make a fresh installation of the framework and an official schema? Just to assure it's a framework issue.

**Comment by StaticXNation** [comment]
I have done so. I put in a fresh install of nutscript. Didn't edit anything, fresh install of HL2RP and still didn't edit anything and the issue still persists.

**Comment by Thadah** [comment]
Alright, try to delete the *nutscript* folder in /data (make a backup first) and retry.

**Comment by rebel1324** [comment]
Something is overriding/nullify L function.
My Heavy CityRP schema is not suffering with this problem.
search if anything actually overriding L function
and try to run https://pastebin.com/1e7NwJth this after all things are loaded.
If it works, It's not our fault.

I'll wait for your future response.

**Comment by StaticXNation** [comment]
Hi, I found out the exact cause of my issue finally. It was this addon that was causing it http://steamcommunity.com/sharedfiles/filedetails/?id=876356702

I extracted it and it seems the addon is overriding the L function. I will alert the creator of the addon about this issue. I apologize for this mishap.

**Comment by rebel1324** [comment]
Niec

2017. 7. 3. 오전 12:55에 "StaticXNation" <notifications@github.com>님이 작성:

Hi, I found out the exact cause of my issue finally. It was this addon that
was causing it http://steamcommunity.com/sharedfiles/filedetails/?id=
876356702

I extracted it and it seems the addon is overriding the L function. I will
alert the creator of the addon about this issue. I apologize for this
mishap.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/rebel1324/NutScript/issues/37#issuecomment-312499993>,
or mute the thread

**Comment by StaticXNation** [comment]
Oops, wrong link. It's this addon, not the other one http://steamcommunity.com/sharedfiles/filedetails/?id=655547376

**Comment by SleepyMode** [comment]
Alright then if you found what the issue was this is done.
