### ISSUE TITLE
Stuck on loading 

### ISSUE THREAD

**Issue by SpookedToad** [rebel1324/NutScript#375]
I have no idea at this point, I am completely stuck with no idea what to do here, ive reinstalled the gamemode twice, ive deleted all my workshop content, Im not even editing files anymore and its still doing it, im not sure if I am doing something wrong or not but a second opinion would be great!

**Comment by bleonheart** [comment]
That issue may have multiple reasons:

Do you have any DarkRP addon installed?

What base schema are you using? 

What edits did you do to it?

By the way, this project has been moved to a new repo:
https://github.com/NutScript/NutScript/

**Comment by SpookedToad** [comment]
No DarkRP addons are installed - but I would be interested in knowing how to do that

a base sample schema I found off a tutorial guide, which just inludes some base nutscript plugins and a citizen id item.lua

aside from adding a faction, none - but I could try downloading a base faction off google and see if maybe my code is just garbo spaghetti 

and noted, appreciate you for lurking here to inform me of that though

**Comment by TovarischPootis** [comment]
Hi, 2 things to note
1. The project has been moved to a new repo, you can find it here:
https://github.com/NutScript/NutScript

The framework is more up to date there, so your issues may be resolved by using the latest release of NS

2. You might find more help and useful help at the NS discord
https://discord.gg/ywYh9kGJ28

The community is generally active and will help you if you cooperate.

Concerning your problem, you most likely have a script error that prevents the framework to properly initialize. You are almost guaranteed to find it somewhere on your server console.
That being said, get the updated framework from the provided repo, follow the installation guide here
https://nutscript.miraheze.org/wiki/Developing_Schema

If you still have any issues, join the discord and provide any errors you have in the support channel

**Comment by SpookedToad** [comment]
Alright, Noted - will certainly get on that, as I said above I wasn't aware the project had moved
