### ISSUE TITLE
inventory:add(item, amount) causes overlapping items sometimes.

### ISSUE THREAD

**Issue by Chancerawr** [rebel1324/NutScript#38]
Generally you see this when you have something a width > 1, An easy way to replicate it is to just inventory:add some 2x2 items all at once. This seems to do concerning things to inventories, but I'm not sure yet. It might not that big of a problem.

**Comment by rebel1324** [comment]
Use inventory:findError() first and confirm the error

sh_item: 38
`-- find out stacked shit
function META:findError()
	for k, v in pairs(self:getItems()) do
		if (v.width == 1 and v.height == 1) then
			continue
		end

		print("Finding error: " .. v.name )
		print("Item Position: " .. v.gridX, v.gridY )
		local x, y;
		for x = v.gridX, v.gridX + v.width - 1 do
			for y = v.gridY, v.gridY + v.height - 1 do
				local item = self.slots[x][y]
				if (item and item.id != v.id) then
					print("Error Found: ".. item.name)
				end
			end
		end
	end
end`

**Comment by Chancerawr** [comment]
When I tested this awhile ago, it found tons. I can check again in a bit though.

**Comment by rebel1324** [comment]
Okay, then give me the reproduction code.

**Comment by Chancerawr** [comment]
https://pastebin.com/NeBgBdS5

**Comment by Chancerawr** [comment]
try that

**Comment by rebel1324** [comment]
This should get fixed with the latest patch
