### ISSUE TITLE
Store Items

### ISSUE THREAD

**Issue by BadWorksFun** [rebel1324/NutScript#40]
Is't possible to have items that only affect certain parts of the model. Like a shirt on affects shirt and leaves everything else okay. or Pants only. or Hat/overcoat only?

**Comment by SleepyMode** [comment]
PAC 3 Outfits.

**Comment by BadWorksFun** [comment]
Does that allow you to affect only certain parts of body? and sell them at store as outfits? If so Thank you!

**Comment by SleepyMode** [comment]
It does.
