### ISSUE TITLE
T-Pose issues

### ISSUE THREAD

**Issue by SandySnail** [rebel1324/NutScript#41]
I recently stared a hl2 nutscript server and all the models for default citizens were fine, I downloaded the schema for it off the offical website. Me being brand new to nutscript I watched a few tutorials on youtube and read up on some forums. Once I was confortable with how the basic factions worked I began experimenting on adding things like models to choose as a citizen when you first load in, I then found out then when you crouch with small firearms (Mainly 9mm pistol and SMG, occasionally shotgun for a few of the models) I then went and deleted the code I copied across from the admin job, this is the only thing I had put in: 

FACTION.models = {
	"models/Humans/Group03/male_02.mdl"
}

(I wanted to have rebel skins available for citizens) After I deleted it and restarted, I made a new character and deleted the old one. I made a new character, gave myself flags and then spawned in a 9mm pistol, I was able to move around and shoot normally having the correct animations, but when I crouched it put me in t-pose but only when I was standing still, it was fine when crouching+movning in any diection.

So far I have tried:

.Deleting the code for the models to choose from and letting NS use the default ones

.Replacing  the models I used with the actual models from Q/Half-Life 2/Characters, same issue occurred

Please would someone respond to this and help me resolve the issue. I understand it's not that major but I would like to try and fix it.

Thanks

**Comment by SleepyMode** [comment]
Please attempt to reinstall the game server.

**Comment by SandySnail** [comment]
I have a fresh installation of nutscript and my server, but the issue is still happening. I have spoken to one of my friends and he says it might be something I need to change in sh_config, but I have looked and I'm not 100% sure.

**Comment by SleepyMode** [comment]
It works just fine for me, are you sure you didn't modify anything that could do it?
What addons do you have alongway in the server?

**Comment by SandySnail** [comment]
I'm pretty sure I didn't modify anything but the schema folder name so it matches the txt file.

This is my content pack if you would like to check, I think it seems better then listing every addon I have.
http://steamcommunity.com/sharedfiles/filedetails/?id=883004790

**Comment by rebel1324** [comment]
There is no problem with current animation system of the Nutscript.
If there is an issue, I think there is no valid model in the server or the model has wrong model path.
