### ISSUE TITLE
Broken Third Person Holstering  

### ISSUE THREAD

**Issue by SirAlexandervonRothenburg** [rebel1324/NutScript#43]
The issue with the holstering system is that in first person it shows weapons holstered, but in third person it shows your character aiming your weapon.  Although it only seems to happen with smgs and rifles, and not pistols

**Comment by Chancerawr** [comment]
This seems to only happen when player anims are being used. 
I did some testing and problem seems to be around here.
https://github.com/rebel1324/NutScript/blob/1.1/gamemode/core/hooks/sh_hooks.lua#L63

I replaced 
if (!nut.config.get("wepAlwaysRaised") and IsValid(weapon) and !client.isWepRaised(client) and client.OnGround(client)) then
	holdType = PLAYER_HOLDTYPE_TRANSLATOR[holdType]
end
with 
holdType = PLAYER_HOLDTYPE_TRANSLATOR[holdType] or "passive"

and it seems to work like it used to (I got this line from an older version of nutscript.)
