### ISSUE TITLE
/chargiveitem doesn't notify the user of the command's success, only the target

### ISSUE THREAD

**Issue by Chancerawr** [rebel1324/NutScript#44]
Pretty minor bug, but annoying nonetheless.
https://github.com/rebel1324/NutScript/blob/1.1/gamemode/core/sh_commands.lua#L275

			if (succ) then
				target:notify("Item successfully created.")
				if(target != client) then
					client:notify("Item successfully created.")
				end
			else
				target:notify(tostring(succ))
				target:notify(tostring(err))
				if(target != client) then
					client:notify(tostring(succ))
					client:notify(tostring(err))
				end
			end

This should fix it.
(succ)

**Comment by SleepyMode** [comment]
Will fix this soon.
Thank you.
