### ISSUE TITLE
/pm gobbles up sentences using lots of apostrophes

### ISSUE THREAD

**Issue by Chancerawr** [rebel1324/NutScript#45]
Here are some examples of the problem. This bug has existed in the nutscript framework for a long time. I believe it is due to how the command concatenates the arguments.
[PM] is what the user receives
[LOG] is the full string of the command

[PM] Event: This is a test sentence.
[LOG] Event used "/pm event This is a test sentence."
Works fine.

[PM] Event: I don't see why not
[LOG] Event used "/pm event I don't see why not"
Works fine

[PM] Event: I t see why I can
[LOG] Event used "/pm event I don't see why I can't"
Clearly there's a problem

[PM] Event: t won t aren meant
[LOG] Event used "/pm event can't won't haven't aren't meant"
Yeah that's not good.

**Comment by Skashh** [comment]
Just tested and I have the same issue.

**Comment by Thadah** [comment]
Confirmed
