### ISSUE TITLE
Config settings save but don't

### ISSUE THREAD

**Issue by Skashh** [rebel1324/NutScript#47]
The config settings you change in the F1 menu save when restarting the server but they don't actually save in the config menu. For example: If I change the server theme color to purple it will save if I restart the server, but it will say it's blue in the config menu.

**Comment by Thadah** [comment]
How weird, I've been testing some new configs I made and they all save, including the color.
Are you sure you are using the latest version of the framework?

**Comment by Chancerawr** [comment]
I think he's talking about the default messages in the config itself. The value is changing, but the value it displays when you reopen the config is always its default value.

**Comment by SleepyMode** [comment]
This is pretty weird.
It sets them to the set value of said parameter, not the default, and only falls to the default if it fails getting the result, 

I'll also like to note it down that when we have tested said issue we were unable to reproduce it and that it works just fine for us.

**Comment by rebel1324** [comment]
Config get saved without any problem. I can't replicate the issue.
