### ISSUE TITLE
Autoresolving RP to Roleplay

### ISSUE THREAD

**Issue by Skashh** [rebel1324/NutScript#50]
Was looking around but I couldn't find where I could disable Nutscript's autoresolving of Roleplay when you have RP in the gamemode name. I'm content on having it be just RP. ;p

**Comment by pmx625** [comment]
That shouldn't happen.
If your SCHEMA.name is "Something RP", it would show up "Something RP" in the servers board.

**Comment by rebel1324** [comment]
We don't have any conversion code in the Framework.
I think it's some kind of translation problem with Garry's Mod.
If you're still having the problem, bring us the image and suspicious code.
