### ISSUE TITLE
Character not loading bug

### ISSUE THREAD

**Issue by 7beat** [rebel1324/NutScript#53]
This is poping up whenewer i try to load character:

[ERROR] gamemodes/nutscript/gamemode/core/meta/sh_character.lua:110: attempt to index local 'v' (a number value)
  1. setup - gamemodes/nutscript/gamemode/core/meta/sh_character.lua:110
   2. unknown - gamemodes/nutscript/gamemode/core/libs/sh_character.lua:550
    3. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
     4. unknown - lua/includes/extensions/net.lua:32

any solutions?

**Comment by rebel1324** [comment]
What the hell are you doing
How can player.GetAll()'s value can return a number?

**Comment by rebel1324** [comment]
Definitely not our problem. You need to get rid of some addons that causes that problem.
