### ISSUE TITLE
Ammosave won't properly load in ammo if its name is all numbers after a server restart

### ISSUE THREAD

**Issue by Chancerawr** [rebel1324/NutScript#55]
Very specific, but still annoying bug. Can be replicated with 357 ammo easily.
Load pistol ammo and 357 ammo.
Wait a bit.
Reconnect.
You will likely have both of the ammo types still.
Restart the server.
You will have pistol ammo but no 357 ammo.

From what I could tell, the issue was that the server wasn't properly loading in 357 from the database as a string, but rather as a number. 
I think I fixed it by doing
client:SetAmmo(v, tostring(k))

But, I'm unsure of if this completely fixes the issue, as I might have misidentified it.

**Comment by rebel1324** [comment]
Maybe the "number" 357 is causing the problem.
I'll fix it to the "string" 357 soon.
