### ISSUE TITLE
Players can see weapons of people in observer

### ISSUE THREAD

**Issue by Chancerawr** [rebel1324/NutScript#62]
Strangely, the person in observer can't see their weapons in thirdperson or in camera, but other players can.

**Comment by rebel1324** [comment]
give me screenshots

**Comment by Chancerawr** [comment]
Further testing seems to indicate that it only happens when you switch to the weapon after entering observer. Here's some pictures

Me:
https://steamuserimages-a.akamaihd.net/ugc/843714289844419405/51A68231660A33284D3A091FC5319FFBFB368F07/
Other guy:
https://steamuserimages-a.akamaihd.net/ugc/853847388986086509/D0DECEBA3EAD4DABFCC33FE869089D00222B5721/

**Comment by rebel1324** [comment]
Hmm. Yeah thanks for the detail.

**Comment by rebel1324** [comment]
This needs to be solved in Engine Level.
If I do make hack about that, Things will go rogue.
