### ISSUE TITLE
Giving a specific Team, User or Group extra character slot.

### ISSUE THREAD

**Issue by clingo** [rebel1324/NutScript#74]
So I was wondering if anyone would know how to give a specific team, group or user extra character slots it seems to be a complicated matter.

**Comment by SleepyMode** [comment]
Greetings!
From what I understood you want some people to be able to make extra characters, but this feature is currently not availabile in vanilla NutScript.
We'll discuss adding it.

**Comment by clingo** [comment]
I don't need help with this I implemented it myself.

**Comment by rebel1324** [comment]
Are you push request the solution? If not, I'm going to make new issue about this.

**Comment by rebel1324** [comment]
any reaction?

**Comment by brianhang** [comment]
You should probably change the character limit check to be a hook which would by default return whether or not a player has less than the maximum number of characters.
