### ISSUE TITLE
Pac 3 error

### ISSUE THREAD

**Issue by Tanoshi-Shinto** [rebel1324/NutScript#80]
[ERROR] addons/pac3/lua/pac3/core/client/base_part.lua:1019: attempt to index field 'last_owner' (a nil value)

HookEntityRender - addons/pac3/lua/pac3/core/client/base_part.lua:1019
v - addons/pac3/lua/pac3/core/client/base_part.lua:286
v - addons/pac3/lua/pac3/core/client/drawing.lua:550
unknown - lua/includes/modules/hook.lua:84
this is made when items are wore and a player dies

**Comment by rebel1324** [comment]
https://github.com/rebel1324/NutScript/commit/edcd7042a3ddc104cb6d45a106c866480461ab88
