### ISSUE TITLE
SRCDS crashing after updating to newest version of nutscript.

### ISSUE THREAD

**Issue by Crossu88** [rebel1324/NutScript#81]
It seems that my dedicated server is not crashing on the schema I've been developing for a while. I happened after I updated to the newest version of nutscript after having not updated for a few months. I don't understand though why the server would crash rather than give me lua errors. Any ideas?

**Comment by rebel1324** [comment]
I need mdmp or detailed information to fiz crash issues

**Comment by pmx625** [comment]
@Crossu88 It is probably your schema or your server. Please provide us with certain details: 

1) Which NS version are you using?
2) What is the base schema you used to build your own (Sample-Schema, HL2RP, etc)?
3) What errors show up in the server console once you start the server/the server is online?

In case you do not respond within 48 hours we will assume this has been fixed and will close this ticket.

Regards,
Pmx
