### ISSUE TITLE
Loading Problem

### ISSUE THREAD

**Issue by Aults1002** [rebel1324/NutScript#83]
When I join my server, it says this, I have not changed the Nutscript folder in any way and I know there is nothing wrong with my Schema.

Failed to load custom font file 'e:/steam/steamapps/common/garrysmod/garrysmod/workshop/resource/fonts/bombard_.ttf'
Failed to load custom font file 'e:/steam/steamapps/common/garrysmod/garrysmod/workshop/resource/fonts/ds-digii.ttf'
Failed to load custom font file 'e:/steam/steamapps/common/garrysmod/garrysmod/workshop/resource/fonts/mrb.ttf'
Failed to load custom font file 'e:\steam\steamapps\common\garrysmod\garrysmod\download\resource\fonts\clearsans-medium.ttf'
Failed to load custom font file 'e:\steam\steamapps\common\garrysmod\garrysmod\cache\workshop\resource\fonts\clearsans-medium.ttf'

I believe it is this, but there are no addons on the server at all either, so I think there is something major wrong with the Nutscript.

**Comment by geferon** [comment]
This is just that your client is missing fonts the server has or that you need.
This may either be caused because your client didn't download properly the server content upon joining or because this fonts aren't even on the server files.
In my opinion, i would completely ignore this errors.
