### ISSUE TITLE
Schema Breaking When Setting Date Before 1950

### ISSUE THREAD

**Issue by SirAlexandervonRothenburg** [rebel1324/NutScript#89]
For some reason when you the schema date before 1950 it breaks the entire f1 menu.  It will make the f1 menu buttons unusable, as well as open the q menu within the q menu and cause script errors.

**Comment by SleepyMode** [comment]
I can't recreate it anymore, still a thing?

**Comment by pmx625** [comment]
@SirAlexandervonRothenburg you have 24 hours to respond. Fail to do that and we will close this issue assuming it is fixed.

**Comment by SleepyMode** [comment]
Closed after 144 hours.
