### ISSUE TITLE
Business Menu needs markdown support

### ISSUE THREAD

**Issue by GeorgeButler** [rebel1324/NutScript#91]
http://steamcommunity.com/sharedfiles/filedetails/?id=1105621603

Business menu looks a little strange without markdown support.

**Comment by rebel1324** [comment]
Oh jesus

**Comment by SleepyMode** [comment]
Still a thing?

**Comment by robinkooli** [comment]
@SleepyMode Yes

**Comment by pmx625** [comment]
@robinkooli do you mind uploading the screenshot again?

**Comment by robinkooli** [comment]
@pmx625 I didn't make this issue, but markdown support would be helpful.

**Comment by pmx625** [comment]
@GeorgeButler Can you upload the screenshot again please?

( @robinkooli I deleted our comments in order to be easier to read more relevant comments here ).

**Comment by SleepyMode** [comment]
@GeorgeButler Could you please upload the screenshot again?

We tried to but kind of failed to recreate it, @robinkooli if you  could give us steps to recreation instead that would be nice aswell.

**Comment by GeorgeButler** [comment]
I don't have the screenshot but If you name an item something like:

<b>Test</b>

It will show up perfectly fine in the world and inventory, but in the business menu it will not appear formatted.

**Comment by pmx625** [comment]
@GeorgeButler Im sorry but we cannot reproduce that. Please try to reproduce it again and send us a screenshot.

**Comment by pmx625** [comment]
The person has not replied within 5 days. This is closed.
