### ISSUE TITLE
Nutscript and CW 2.0

### ISSUE THREAD

**Issue by ChayseRamsay** [rebel1324/NutScript#92]
So, I don't know if this is me being an idiot, but for some reason when I've tried to add CW firearms as equipable items, it just straight up doesn't work. I do however get a very large error spam in the console;

`[NutScript] Item 'cw_g4p_masada_acr' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_g4p_mp412_rex' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_g4p_usp40' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_g4p_xm8' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_kriss_5_vector' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_l115' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_l85a2' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_m14' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_m1911' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_m249_official' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_m3super90' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_mac11' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_makarov' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_mp5' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_mr96' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_p99' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_scarh' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_shorty' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_ump45' has a non-existent base! (base_weapon)
[NutScript] Item 'cw_vss' has a non-existent base! (base_weapon)`etc.

As an additional note, is it possible to add a context menu check to the weapon select system? It'd solve the issues of putting attachments on CW firearms entirely.

**Comment by rebel1324** [comment]
The Server/Framework/Schema does not have base_weapon

Windows 10용 메일에서 보냄

보낸 사람: Chayse Ramsay
보낸 날짜: 2017년 8월 21일 월요일 오전 11:48
받는 사람: rebel1324/NutScript
참조: Subscribed
제목: [rebel1324/NutScript] Nutscript and CW 2.0 (#92)

So, I don't know if this is me being an idiot, but for some reason when I've tried to add CW firearms as equipable items, it just straight up doesn't work. I do however get a very large error spam in the console;
[NutScript] Item 'cw_g4p_masada_acr' has a non-existent base! (base_weapon) [NutScript] Item 'cw_g4p_mp412_rex' has a non-existent base! (base_weapon) [NutScript] Item 'cw_g4p_usp40' has a non-existent base! (base_weapon) [NutScript] Item 'cw_g4p_xm8' has a non-existent base! (base_weapon) [NutScript] Item 'cw_kriss_5_vector' has a non-existent base! (base_weapon) [NutScript] Item 'cw_l115' has a non-existent base! (base_weapon) [NutScript] Item 'cw_l85a2' has a non-existent base! (base_weapon) [NutScript] Item 'cw_m14' has a non-existent base! (base_weapon) [NutScript] Item 'cw_m1911' has a non-existent base! (base_weapon) [NutScript] Item 'cw_m249_official' has a non-existent base! (base_weapon) [NutScript] Item 'cw_m3super90' has a non-existent base! (base_weapon) [NutScript] Item 'cw_mac11' has a non-existent base! (base_weapon) [NutScript] Item 'cw_makarov' has a non-existent base! (base_weapon) [NutScript] Item 'cw_mp5' has a non-existent base! (base_weapon) [NutScript] Item 'cw_mr96' has a non-existent base! (base_weapon) [NutScript] Item 'cw_p99' has a non-existent base! (base_weapon) [NutScript] Item 'cw_scarh' has a non-existent base! (base_weapon) [NutScript] Item 'cw_shorty' has a non-existent base! (base_weapon) [NutScript] Item 'cw_ump45' has a non-existent base! (base_weapon) [NutScript] Item 'cw_vss' has a non-existent base! (base_weapon)etc.
As an additional note, is it possible to add a context menu check to the weapon select system? It'd solve the issues of putting attachments on CW firearms entirely.

**Comment by ChayseRamsay** [comment]
I have no idea what base_weapon is or why it'd need it. All it should be doing is giving the player the CW weapon attached to the item, no?

**Comment by rebel1324** [comment]
You deleted/modified item/base/sh_weapons.lua in Nutscript Framework and I can’t reply anything about modified Nutscript Framework. Modifing the core means ‘I know what I’m doing’.

Windows 10용 메일에서 보냄

보낸 사람: Chayse Ramsay
보낸 날짜: 2017년 8월 21일 월요일 오전 11:56
받는 사람: rebel1324/NutScript
참조: Kyu Yeon Lee; Comment
제목: Re: [rebel1324/NutScript] Nutscript and CW 2.0 (#92)

I have no idea what base_weapon is or why it'd need it. All it should be doing is giving the player the CW weapon attached to the item, no?

**Comment by ChayseRamsay** [comment]
![](https://image.prntscr.com/image/liguE0cmQ9_NXzUl22mSUg.png)
I haven't deleted sh_weapons.lua, nor have I even touched it. This isn't the case of me modifying the core, because I haven't touched the core whatsoever. Entirely fresh 1.1 download, too.

**Comment by rebel1324** [comment]
Then there is only one suspicious point, Check all of Error Messages in the Server Console, there might be some error that preventing framework from loading all of it’s files.

Windows 10용 메일에서 보냄

보낸 사람: Chayse Ramsay
보낸 날짜: 2017년 8월 21일 월요일 오후 12:02
받는 사람: rebel1324/NutScript
참조: Kyu Yeon Lee; Comment
제목: Re: [rebel1324/NutScript] Nutscript and CW 2.0 (#92)


I haven't deleted sh_weapons.lua, nor have I even touched it. This isn't the case of me modifying the core, because I haven't touched the core whatsoever. Entirely fresh 1.1 download, too.

**Comment by ChayseRamsay** [comment]
On a hunch I tried renaming sh_weapons.lua to sh_weapon.lua and all of a sudden no more errors.
