### ISSUE TITLE
TFA Weapons and Ammo

### ISSUE THREAD

**Issue by Ripskilt** [rebel1324/NutScript#97]
I am trying to make ammo work with TFA weapons, how ever I am having some issues. I'll list them below.

TFA weapons when un-equipt and re-equipted get back their lost ammo, you can continue to do this to get unlimited ammo.

TFA Ammo - When I try to make ammo for the weapons (I only tried with the Sako 85 from the pack NMRIH) it does not work, they go into oblivion and nothing happens.

Code below -

Weapons -
ITEM.name = "Sako 85"
ITEM.desc = "A old worn hunting rifle"
ITEM.model = Model ("models/weapons/tfa_nmrih/w_fa_sako85.mdl")
ITEM.class = "tfa_nmrih_sako"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 5000
ITEM.flag = "y"

AMMO -

ITEM.name = ".357 Sniper Rounds"
ITEM.model = "models/items/sniper_round_box.mdl"
ITEM.ammo = "tfa_ammo_sniper_rounds"
ITEM.ammoAmount = 30
ITEM.ammoDesc = "A Box that contains %s of .357 Sniper Rounds"
ITEM.price = 10
ITEM.category = "Ammunition"
ITEM.flag = "y"

**Comment by Chancerawr** [comment]
When you look in the swep, what ammo does it say the weapon uses under PrimaryAmmo? I don't think it's going to be tfa_ammo_sniper_rounds. You need to find out what that is, and set ITEM.ammo to it. Also you probably want to post this type of thing in the NS discord instead of here.

**Comment by Ripskilt** [comment]
It says Sniper Rounds under the TFA Ammo area, and is what gets used for the weapons, so do you not copy to clipboard and paste it there? Someone told me thats what to do, but if not then im a moron.

**Comment by Chancerawr** [comment]
I think what you have there is the entity name for the ammo box, which is different. You need to open the weapon's lua file and see what it uses in there.

**Comment by Ripskilt** [comment]
Ahh, alright let me take a quick peek.

SWEP.Primary.Ammo = "SniperPenetratedRound"

Yep, seems that is it, let me give it a try here and I'll let ya' know.

**Comment by Ripskilt** [comment]
Alright cool, the ammo loads into the fire arms now, awesome thank you.

How ever I have one more think I'd like help with if at all possible.

If the weapons are un-equip then re-equip, that person gets around 20-30 rounds given to them from no where. Do you know a way to fix it?

**Comment by Chancerawr** [comment]
Go into the weapon's code and set the DefaultClip to 0.
