### ISSUE TITLE
When I set a characters faction using setFaction() it doesn't save in database.

### ISSUE THREAD

**Issue by pineappleAsquares** [rebel1324/NutScript#98]
So I am setting up a command where it sets the clients faction when the command is entered but it changes it but doesn't update it in the database or changes back to his previous faction if they switch characters too. Can this be fixed like when you use plytransfer it saves I think I need to update the database but I am not sure how to go about doing this?

**Comment by geferon** [comment]
I freaking told you on discord.
Do it the same way as Nutscript itself does it:
https://github.com/rebel1324/NutScript/blob/1.1/gamemode/core/sh_commands.lua#L649-L685

**Comment by pineappleAsquares** [comment]
my discord notifcations dont work so I thought I was getting ignored sorry D:
