### ISSUE TITLE
3D Voice not working

### ISSUE THREAD

**Issue by lljsullins** [rebel1324/NutScript#99]
This has not been working since I got the new nutscript update back in May. I've been trying to fix this ever since. This is really important to the Roleplay access in the gamemodes that are important. I hope that this get's fixed soon

Thanks,
Liam

**Comment by brianhang** [comment]
Probably related to https://github.com/rebel1324/NutScript/commit/cf4294c239422d810283c91a841510288370fb6f. Maybe 3D voice should've been its own config which will set the second return value.

**Comment by Thadah** [comment]
Whoops, sorry for my mistake, I've must have gotten confused by the values with the same name

**Comment by SleepyMode** [comment]
Any updates?
@Thadah

**Comment by Thadah** [comment]
I can get to it this weekend, but I'll need people to test it

**Comment by lljsullins** [comment]
I'd join. 
@Thadah

**Comment by Thadah** [comment]
Opened #104

**Comment by supermicronde3** [comment]
Replace in gamemodes/nutscript/gamemode/hooks/sv_hooks.lua the function "GM:PlayerCanHearPlayersVoice"  by :

`function GM:PlayerCanHearPlayersVoice(listener, speaker)
	local allowVoice = nut.config.get("allowVoice")
	
	if math.sqrt(listener:GetPos():DistToSqr(speaker:GetPos())) > nut.config.get("chatRange") then
		return false;
	end
	
	return allowVoice , allowVoice
end`

**Comment by brianhang** [comment]
You should really just compare the squared `voiceDistance` value. Also, mind the inconsistent space after `allowVoice`, no parentheses around the if condition, and semicolon.

**Comment by supermicronde3** [comment]
I use a maxDistance value because old nutscript versions dont have the a voiceDistance

**Comment by brianhang** [comment]
`sqrt` is an expensive function to use so you should instead compare with squared values.

**Comment by supermicronde3** [comment]
...

**Comment by supermicronde3** [comment]
What is the hook for when the config are modified ?

**Comment by pmx625** [comment]
@Thadah How is this going?

**Comment by Thadah** [comment]
A pull request made by @supermicronde3 fixed it

**Comment by pmx625** [comment]
**Alright! I will close it.**
